insert into MOCK_DATA (Movie) values ('Report, The (Gozaresh)');
insert into MOCK_DATA (Movie) values ('Great Expectations');
insert into MOCK_DATA (Movie) values ('True Legend (Su Qi-Er)');
insert into MOCK_DATA (Movie) values ('Whom the Gods Wish to Destroy (Nibelungen, Teil 1: Siegfried, Die)');
insert into MOCK_DATA (Movie) values ('For a Good Time, Call...');
insert into MOCK_DATA (Movie) values ('Badlanders, The');
insert into MOCK_DATA (Movie) values ('Lettera Amorosa');
insert into MOCK_DATA (Movie) values ('Killing Us Softly 3');
insert into MOCK_DATA (Movie) values ('Our Vinyl Weighs a Ton: This Is Stones Throw Records');
insert into MOCK_DATA (Movie) values ('Death at a Funeral');
insert into MOCK_DATA (Movie) values ('Smart Money');
insert into MOCK_DATA (Movie) values ('I Spit on Your Grave 2 ');
insert into MOCK_DATA (Movie) values ('Mitchell');
insert into MOCK_DATA (Movie) values ('Intact (Intacto)');
insert into MOCK_DATA (Movie) values ('Hatchet II');
insert into MOCK_DATA (Movie) values ('Final Conflict, The (a.k.a. Omen III: The Final Conflict)');
insert into MOCK_DATA (Movie) values ('Honey, I Shrunk the Kids');
insert into MOCK_DATA (Movie) values ('Come Have Coffee with Us');
insert into MOCK_DATA (Movie) values ('Who Framed Roger Rabbit?');
insert into MOCK_DATA (Movie) values ('Spanish Earth, The');
insert into MOCK_DATA (Movie) values ('Way Out West');
insert into MOCK_DATA (Movie) values ('Hero at Large');
insert into MOCK_DATA (Movie) values ('All About Eve');
insert into MOCK_DATA (Movie) values ('Stars in My Crown');
insert into MOCK_DATA (Movie) values ('Americano');
insert into MOCK_DATA (Movie) values ('B.T.K.');
insert into MOCK_DATA (Movie) values ('Children of Glory (Szabadság, szerelem)');
insert into MOCK_DATA (Movie) values ('Forever, Darling');
insert into MOCK_DATA (Movie) values ('Flash Point (a.k.a. Flashpoint) (Dou fo sin)');
insert into MOCK_DATA (Movie) values ('Front Page, The');
insert into MOCK_DATA (Movie) values ('Sister (L''enfant d''en haut)');
insert into MOCK_DATA (Movie) values ('Grease 2');
insert into MOCK_DATA (Movie) values ('Born to Be Bad');
insert into MOCK_DATA (Movie) values ('Oh, Susanna!');
insert into MOCK_DATA (Movie) values ('Abyss, The');
insert into MOCK_DATA (Movie) values ('Bring on the Night');
insert into MOCK_DATA (Movie) values ('Italian for Beginners (Italiensk for begyndere)');
insert into MOCK_DATA (Movie) values ('Bell for Adano, A (John Hersey''s A Bell for Adano)');
insert into MOCK_DATA (Movie) values ('Secret of the Wings');
insert into MOCK_DATA (Movie) values ('Leaves from Satan''s Book (Blade af Satans bog)');
insert into MOCK_DATA (Movie) values ('Fahrenheit 9/11');
insert into MOCK_DATA (Movie) values ('None But the Brave');
insert into MOCK_DATA (Movie) values ('Partners in Crime (Associés contre le crime...)');
insert into MOCK_DATA (Movie) values ('J. Gang Meets Dynamite Harry, The (Jönssonligan & DynamitHarry)');
insert into MOCK_DATA (Movie) values ('And Then Came Lola');
insert into MOCK_DATA (Movie) values ('The Other Side of the Mountain');
insert into MOCK_DATA (Movie) values ('Namesake, The');
insert into MOCK_DATA (Movie) values ('Year Zero: The Silent Death of Cambodia');
insert into MOCK_DATA (Movie) values ('Summer''s Tale, A (Conte d''été)');
insert into MOCK_DATA (Movie) values ('Svidd Neger');
insert into MOCK_DATA (Movie) values ('Slow Burn');
insert into MOCK_DATA (Movie) values ('Forgotten, The');
insert into MOCK_DATA (Movie) values ('Solaris (Solyaris)');
insert into MOCK_DATA (Movie) values ('24 7: Twenty Four Seven');
insert into MOCK_DATA (Movie) values ('It Happened One Night');
insert into MOCK_DATA (Movie) values ('3 Ninjas Knuckle Up');
insert into MOCK_DATA (Movie) values ('Ploy');
insert into MOCK_DATA (Movie) values ('Karan Arjun');
insert into MOCK_DATA (Movie) values ('Radio Flyer');
insert into MOCK_DATA (Movie) values ('Family, The');
insert into MOCK_DATA (Movie) values ('Rolling Thunder');
insert into MOCK_DATA (Movie) values ('Catwalk');
insert into MOCK_DATA (Movie) values ('Case of You, A');
insert into MOCK_DATA (Movie) values ('Macbeth in Manhattan');
insert into MOCK_DATA (Movie) values ('Giant of Marathon, The (Battaglia di Maratona, La)');
insert into MOCK_DATA (Movie) values ('My Piece of the Pie (Ma part du gâteau)');
insert into MOCK_DATA (Movie) values ('Arachnophobia');
insert into MOCK_DATA (Movie) values ('Wedding Crashers');
insert into MOCK_DATA (Movie) values ('Quest, The');
insert into MOCK_DATA (Movie) values ('Spider-Man: The Ultimate Villain Showdown');
insert into MOCK_DATA (Movie) values ('On the Riviera');
insert into MOCK_DATA (Movie) values ('Cremaster 2');
insert into MOCK_DATA (Movie) values ('Life for Sale (Kotirauha)');
insert into MOCK_DATA (Movie) values ('Nom de code : Rose');
insert into MOCK_DATA (Movie) values ('TWA Flight 800 ');
insert into MOCK_DATA (Movie) values ('Veronica Guerin');
insert into MOCK_DATA (Movie) values ('Sex and the City 2');
insert into MOCK_DATA (Movie) values ('Cassandra Crossing, The');
insert into MOCK_DATA (Movie) values ('Electric Dragon 80.000 V');
insert into MOCK_DATA (Movie) values ('For a Woman (Pour une femme)');
insert into MOCK_DATA (Movie) values ('Houseguest');
insert into MOCK_DATA (Movie) values ('Jesus Henry Christ');
insert into MOCK_DATA (Movie) values ('Man Who Fell to Earth, The');
insert into MOCK_DATA (Movie) values ('Repeaters ');
insert into MOCK_DATA (Movie) values ('Fright to the Finish');
insert into MOCK_DATA (Movie) values ('Slipping-Down Life, A');
insert into MOCK_DATA (Movie) values ('Of Love and Shadows');
insert into MOCK_DATA (Movie) values ('Woody Allen: A Documentary');
insert into MOCK_DATA (Movie) values ('Free Birds');
insert into MOCK_DATA (Movie) values ('Blue Angel, The');
insert into MOCK_DATA (Movie) values ('Other Sister, The');
insert into MOCK_DATA (Movie) values ('Never Give a Sucker an Even Break');
insert into MOCK_DATA (Movie) values ('Eila, Rampe and Likka');
insert into MOCK_DATA (Movie) values ('Jungo Goes Bananas: Jungo III (Jungledyret Hugo: Fræk, flabet og fri)');
insert into MOCK_DATA (Movie) values ('20 Million Miles to Earth');
insert into MOCK_DATA (Movie) values ('Fuck');
insert into MOCK_DATA (Movie) values ('Dead Man Running');
insert into MOCK_DATA (Movie) values ('St Trinian''s 2: The Legend of Fritton''s Gold');
insert into MOCK_DATA (Movie) values ('Public Access');
insert into MOCK_DATA (Movie) values ('Batman Beyond: Return of the Joker');
insert into MOCK_DATA (Movie) values ('Killer Is Loose, The');
insert into MOCK_DATA (Movie) values ('Marc Pease Experience, The');
insert into MOCK_DATA (Movie) values ('Story of Luke, The');
insert into MOCK_DATA (Movie) values ('Anne of Green Gables: The Sequel (a.k.a. Anne of Avonlea)');
insert into MOCK_DATA (Movie) values ('From Russia with Love');
insert into MOCK_DATA (Movie) values ('Short Sharp Shock (Kurz und schmerzlos) ');
insert into MOCK_DATA (Movie) values ('Body of Lies');
insert into MOCK_DATA (Movie) values ('Welcome to Mooseport');
insert into MOCK_DATA (Movie) values ('Blood Beast Terror, The');
insert into MOCK_DATA (Movie) values ('Student Bodies');
insert into MOCK_DATA (Movie) values ('Bird of Prey');
insert into MOCK_DATA (Movie) values ('Seven Up!');
insert into MOCK_DATA (Movie) values ('Pit and the Pendulum, The');
insert into MOCK_DATA (Movie) values ('Norm MacDonald: Me Doing Standup');
insert into MOCK_DATA (Movie) values ('Liberal Arts');
insert into MOCK_DATA (Movie) values ('Revenge of Frankenstein, The');
insert into MOCK_DATA (Movie) values ('Collector, The');
insert into MOCK_DATA (Movie) values ('Airspeed');
insert into MOCK_DATA (Movie) values ('Bucky Larson: Born to Be a Star');
insert into MOCK_DATA (Movie) values ('Luther');
insert into MOCK_DATA (Movie) values ('Misérables, Les');
insert into MOCK_DATA (Movie) values ('Parasites, Les');
insert into MOCK_DATA (Movie) values ('Young Black Stallion, The');
insert into MOCK_DATA (Movie) values ('Mad Monster Party?');
insert into MOCK_DATA (Movie) values ('Hombre');
insert into MOCK_DATA (Movie) values ('After Hours');
insert into MOCK_DATA (Movie) values ('Mask of Zorro, The');
insert into MOCK_DATA (Movie) values ('Thesis (Tesis)');
insert into MOCK_DATA (Movie) values ('Child''s Play 2');
insert into MOCK_DATA (Movie) values ('Trouble with the Curve');
insert into MOCK_DATA (Movie) values ('Mickey, Donald, Goofy: The Three Musketeers');
insert into MOCK_DATA (Movie) values ('Lifted');
insert into MOCK_DATA (Movie) values ('Plutonium Circus');
insert into MOCK_DATA (Movie) values ('Older Brother, Younger Sister (Ani imôto)');
insert into MOCK_DATA (Movie) values ('Cameraman''s Revenge, The (Mest kinematograficheskogo operatora)');
insert into MOCK_DATA (Movie) values ('Mobsters');
insert into MOCK_DATA (Movie) values ('Last Orders');
insert into MOCK_DATA (Movie) values ('I, Madman');
insert into MOCK_DATA (Movie) values ('Wild Child, The (Enfant sauvage, L'')');
insert into MOCK_DATA (Movie) values ('Notorious');
insert into MOCK_DATA (Movie) values ('Coupe de Ville');
insert into MOCK_DATA (Movie) values ('East is East');
insert into MOCK_DATA (Movie) values ('Blue Umbrella, The');
insert into MOCK_DATA (Movie) values ('Evangelion: 1.0 You Are (Not) Alone (Evangerion shin gekijôban: Jo)');
insert into MOCK_DATA (Movie) values ('Brother Rat');
insert into MOCK_DATA (Movie) values ('Wild Party, The');
insert into MOCK_DATA (Movie) values ('Viimeiset rotannahat ');
insert into MOCK_DATA (Movie) values ('Above and Beyond');
insert into MOCK_DATA (Movie) values ('Champagne for Caesar');
insert into MOCK_DATA (Movie) values ('West Point Story, The');
insert into MOCK_DATA (Movie) values ('Kiss Kiss - Bang Bang');
insert into MOCK_DATA (Movie) values ('Critters 4');
insert into MOCK_DATA (Movie) values ('Another Thin Man');
insert into MOCK_DATA (Movie) values ('Exit Smiling');
insert into MOCK_DATA (Movie) values ('Quick Change');
insert into MOCK_DATA (Movie) values ('At the River I Stand');
insert into MOCK_DATA (Movie) values ('100 Feet');
insert into MOCK_DATA (Movie) values ('Blood Night: The Legend of Mary Hatchet (Blood Night)');
insert into MOCK_DATA (Movie) values ('Dumbo');
insert into MOCK_DATA (Movie) values ('Walk on the Wild Side');
insert into MOCK_DATA (Movie) values ('Hand, The');
insert into MOCK_DATA (Movie) values ('I''m a Cyborg, But That''s OK (Saibogujiman kwenchana)');
insert into MOCK_DATA (Movie) values ('Nobody Owns Me (Mig äger ingen)');
insert into MOCK_DATA (Movie) values ('Memory');
insert into MOCK_DATA (Movie) values ('2 Days in the Valley');
insert into MOCK_DATA (Movie) values ('All''s Faire in Love');
insert into MOCK_DATA (Movie) values ('Dolores Claiborne');
insert into MOCK_DATA (Movie) values ('Fool''s Gold');
insert into MOCK_DATA (Movie) values ('Bone Collector, The');
insert into MOCK_DATA (Movie) values ('The Invitation');
insert into MOCK_DATA (Movie) values ('Trip to the Moon, A (Voyage dans la lune, Le)');
insert into MOCK_DATA (Movie) values ('Monsters University');
insert into MOCK_DATA (Movie) values ('Queen Sized');
insert into MOCK_DATA (Movie) values ('Enemies: A Love Story');
insert into MOCK_DATA (Movie) values ('Trapeze');
insert into MOCK_DATA (Movie) values ('Christmas Carol, A');
insert into MOCK_DATA (Movie) values ('Young Poisoner''s Handbook, The');
insert into MOCK_DATA (Movie) values ('Sons of Katie Elder');
insert into MOCK_DATA (Movie) values ('Bravo Two Zero ');
insert into MOCK_DATA (Movie) values ('Wednesday!, A');
insert into MOCK_DATA (Movie) values ('Wisconsin Death Trip');
insert into MOCK_DATA (Movie) values ('Newsfront');
insert into MOCK_DATA (Movie) values ('Scarface');
insert into MOCK_DATA (Movie) values ('Between Heaven and Hell');
insert into MOCK_DATA (Movie) values ('Pudana Last of the Line (Sukunsa viimeinen)');
insert into MOCK_DATA (Movie) values ('Speed Of Thought, The');
insert into MOCK_DATA (Movie) values ('Knight of Cups');
insert into MOCK_DATA (Movie) values ('The .44 Specialist');
insert into MOCK_DATA (Movie) values ('Grouse');
insert into MOCK_DATA (Movie) values ('Time of Your Life, The');
insert into MOCK_DATA (Movie) values ('Cowboy and the Lady, The');
insert into MOCK_DATA (Movie) values ('Lilian''s Story');
insert into MOCK_DATA (Movie) values ('Losing Chase');
insert into MOCK_DATA (Movie) values ('Heart Condition');
insert into MOCK_DATA (Movie) values ('Words and Pictures');
insert into MOCK_DATA (Movie) values ('The Jackie Robinson Story');
insert into MOCK_DATA (Movie) values ('Love with the Proper Stranger');
insert into MOCK_DATA (Movie) values ('Delta Force, The');
insert into MOCK_DATA (Movie) values ('Kolka Cool');
insert into MOCK_DATA (Movie) values ('Dragon: The Bruce Lee Story');
insert into MOCK_DATA (Movie) values ('Legend of the Eight Samurai (Satomi hakken-den)');
insert into MOCK_DATA (Movie) values ('Open Water');
insert into MOCK_DATA (Movie) values ('Trust Us, This Is All Made Up');
insert into MOCK_DATA (Movie) values ('Everybody''s Fine (Stanno tutti bene)');
insert into MOCK_DATA (Movie) values ('Black Eagle');
insert into MOCK_DATA (Movie) values ('Dr. Akagi (Kanzo sensei)');
insert into MOCK_DATA (Movie) values ('Inspectors, The');
insert into MOCK_DATA (Movie) values ('Handful of Dust, A');
insert into MOCK_DATA (Movie) values ('Morituri');
insert into MOCK_DATA (Movie) values ('K-9');
insert into MOCK_DATA (Movie) values ('Over the Brooklyn Bridge');
insert into MOCK_DATA (Movie) values ('Jin Roh: The Wolf Brigade (Jin-Rô)');
insert into MOCK_DATA (Movie) values ('King of Marvin Gardens, The');
insert into MOCK_DATA (Movie) values ('Doctor and the Devils, The');
insert into MOCK_DATA (Movie) values ('Home for Christmas (Hjem til jul)');
insert into MOCK_DATA (Movie) values ('Fiorile');
insert into MOCK_DATA (Movie) values ('Rat');
insert into MOCK_DATA (Movie) values ('Hotel Very Welcome');
insert into MOCK_DATA (Movie) values ('Illusion Of Blood');
insert into MOCK_DATA (Movie) values ('List of Adrian Messenger, The');
insert into MOCK_DATA (Movie) values ('Goodbye, Dragon Inn (Bu san)');
insert into MOCK_DATA (Movie) values ('Prison (Fängelse) ');
insert into MOCK_DATA (Movie) values ('Top Floor Left Wing (Dernier étage gauche gauche)');
insert into MOCK_DATA (Movie) values ('Quick and the Dead, The');
insert into MOCK_DATA (Movie) values ('Phase 7');
insert into MOCK_DATA (Movie) values ('Healing');
insert into MOCK_DATA (Movie) values ('90 Minutes (90 minutter)');
insert into MOCK_DATA (Movie) values ('Fear and Trembling (Stupeur et tremblements)');
insert into MOCK_DATA (Movie) values ('Queen of the Mountains');
insert into MOCK_DATA (Movie) values ('Hostage');
insert into MOCK_DATA (Movie) values ('Trailer Park Boys');
insert into MOCK_DATA (Movie) values ('I Start Counting');
insert into MOCK_DATA (Movie) values ('Extremities');
insert into MOCK_DATA (Movie) values ('Razorback');
insert into MOCK_DATA (Movie) values ('Blindsight');
insert into MOCK_DATA (Movie) values ('Slaughter Rule, The');
insert into MOCK_DATA (Movie) values ('I Origins');
insert into MOCK_DATA (Movie) values ('Men, The');
insert into MOCK_DATA (Movie) values ('Three Lives of Thomasina, The');
insert into MOCK_DATA (Movie) values ('Tammy and the Bachelor');
insert into MOCK_DATA (Movie) values ('Sanctum');
insert into MOCK_DATA (Movie) values ('Woman in the Fifth, The (Femme du Vème, La)');
insert into MOCK_DATA (Movie) values ('Best Boy');
insert into MOCK_DATA (Movie) values ('Merchant of Four Seasons, The (Händler der vier Jahreszeiten)');
insert into MOCK_DATA (Movie) values ('From Up on Poppy Hill (Kokuriko-zaka kara)');
insert into MOCK_DATA (Movie) values ('Suing the Devil');
insert into MOCK_DATA (Movie) values ('Tarzan''s New York Adventure');
insert into MOCK_DATA (Movie) values ('Star Trek VI: The Undiscovered Country');
insert into MOCK_DATA (Movie) values ('Session 9');
insert into MOCK_DATA (Movie) values ('Lasa y Zabala');
insert into MOCK_DATA (Movie) values ('Sweeney Todd');
insert into MOCK_DATA (Movie) values ('Savannah Smiles');
insert into MOCK_DATA (Movie) values ('You Don''t Know Jack');
insert into MOCK_DATA (Movie) values ('Monster''s Ball');
insert into MOCK_DATA (Movie) values ('Déjà Vu');
insert into MOCK_DATA (Movie) values ('Adam''s Apples (Adams æbler)');
insert into MOCK_DATA (Movie) values ('The Hunting Ground');
insert into MOCK_DATA (Movie) values ('Little Romance, A');
insert into MOCK_DATA (Movie) values ('Everything');
insert into MOCK_DATA (Movie) values ('Girlhood');
insert into MOCK_DATA (Movie) values ('Lasa y Zabala');
insert into MOCK_DATA (Movie) values ('300: Rise of an Empire');
insert into MOCK_DATA (Movie) values ('Is Anybody There?');
insert into MOCK_DATA (Movie) values ('Warm December, A');
insert into MOCK_DATA (Movie) values ('Hole, The');
insert into MOCK_DATA (Movie) values ('Ben-Hur: A Tale of the Christ');
insert into MOCK_DATA (Movie) values ('Purple Rain');
insert into MOCK_DATA (Movie) values ('Blood for Dracula (Andy Warhol''s Dracula)');
insert into MOCK_DATA (Movie) values ('Daffy Duck''s Quackbusters');
insert into MOCK_DATA (Movie) values ('Emperor''s New Groove, The');
insert into MOCK_DATA (Movie) values ('Bothersome Man, The (Brysomme mannen, Den)');
insert into MOCK_DATA (Movie) values ('Gaucho, The');
insert into MOCK_DATA (Movie) values ('This Is My Life');
insert into MOCK_DATA (Movie) values ('Pure');
insert into MOCK_DATA (Movie) values ('Trigun: Badlands Rumble');
insert into MOCK_DATA (Movie) values ('Showrunners: The Art of Running a TV Show');
insert into MOCK_DATA (Movie) values ('Criminal Life of Archibaldo de la Cruz, The (Ensayo de un crimen)');
insert into MOCK_DATA (Movie) values ('Sword of Gideon');
insert into MOCK_DATA (Movie) values ('Camille Claudel');
insert into MOCK_DATA (Movie) values ('25th Hour');
insert into MOCK_DATA (Movie) values ('One Night with the King');
insert into MOCK_DATA (Movie) values ('Passage to India, A');
insert into MOCK_DATA (Movie) values ('Noise');
insert into MOCK_DATA (Movie) values ('Mole People, The');
insert into MOCK_DATA (Movie) values ('Chill Factor');
insert into MOCK_DATA (Movie) values ('Strange Planet');
insert into MOCK_DATA (Movie) values ('New Kind of Love, A');
insert into MOCK_DATA (Movie) values ('Tiger Brigades, The (Les brigades du Tigre)');
insert into MOCK_DATA (Movie) values ('Savannah Smiles');
insert into MOCK_DATA (Movie) values ('All About Anna');
insert into MOCK_DATA (Movie) values ('Don''t Look in the Basement!');
insert into MOCK_DATA (Movie) values ('Fire in the Sky');
insert into MOCK_DATA (Movie) values ('Devil Bat, The');
insert into MOCK_DATA (Movie) values ('X');
insert into MOCK_DATA (Movie) values ('Lawn Dogs');
insert into MOCK_DATA (Movie) values ('Fortress');
insert into MOCK_DATA (Movie) values ('Zen Noir');
insert into MOCK_DATA (Movie) values ('Shadow of the Vampire');
insert into MOCK_DATA (Movie) values ('One Hour with You');
insert into MOCK_DATA (Movie) values ('Judas Kiss');
insert into MOCK_DATA (Movie) values ('Pete Smalls Is Dead');
insert into MOCK_DATA (Movie) values ('Spaghetti West, The');
insert into MOCK_DATA (Movie) values ('Watchmen');
insert into MOCK_DATA (Movie) values ('Human Condition II, The (Ningen no joken II)');
insert into MOCK_DATA (Movie) values ('We Are Marshall');
insert into MOCK_DATA (Movie) values ('Sex, Lies, and Videotape');
insert into MOCK_DATA (Movie) values ('Clerks II');
insert into MOCK_DATA (Movie) values ('They Call Me Trinity');
insert into MOCK_DATA (Movie) values ('Kisses');
insert into MOCK_DATA (Movie) values ('Five Weeks in a Balloon');
insert into MOCK_DATA (Movie) values ('Bruno (Dress Code, The)');
insert into MOCK_DATA (Movie) values ('Frankenstein Syndrome, The');
insert into MOCK_DATA (Movie) values ('Ride the Pink Horse');
insert into MOCK_DATA (Movie) values ('Mummy''s Curse, The');
insert into MOCK_DATA (Movie) values ('Flesh and Bone');
insert into MOCK_DATA (Movie) values ('Open Water');
insert into MOCK_DATA (Movie) values ('Osmosis (Osmose)');
insert into MOCK_DATA (Movie) values ('Amazing Journey: The Story of The Who');
insert into MOCK_DATA (Movie) values ('What''s Up, Tiger Lily?');
insert into MOCK_DATA (Movie) values ('Superman and the Mole-Men');
insert into MOCK_DATA (Movie) values ('Someday This Pain Will Be Useful to You');
insert into MOCK_DATA (Movie) values ('Holiday Wishes');
insert into MOCK_DATA (Movie) values ('Guilty as Sin');
insert into MOCK_DATA (Movie) values ('The Clowns');
insert into MOCK_DATA (Movie) values ('Kevin Nealon: Now Hear Me Out!');
insert into MOCK_DATA (Movie) values ('Kid Cannabis');
insert into MOCK_DATA (Movie) values ('Chasers, The (Jakten)');
insert into MOCK_DATA (Movie) values ('Eye 2, The (Gin gwai 2)');
insert into MOCK_DATA (Movie) values ('Resident Evil: Apocalypse');
insert into MOCK_DATA (Movie) values ('Kariera Nikosia Dyzmy');
insert into MOCK_DATA (Movie) values ('Everyone''s Hero');
insert into MOCK_DATA (Movie) values ('Bestiaire');
insert into MOCK_DATA (Movie) values ('Bananas!*');
insert into MOCK_DATA (Movie) values ('Burton and Taylor');
insert into MOCK_DATA (Movie) values ('Bait');
insert into MOCK_DATA (Movie) values ('Lassie Come Home');
insert into MOCK_DATA (Movie) values ('Killing Floor, The');
insert into MOCK_DATA (Movie) values ('Girl Most Likely');
insert into MOCK_DATA (Movie) values ('Forty-first, The (Sorok pervyy)');
insert into MOCK_DATA (Movie) values ('Cobra Woman');
insert into MOCK_DATA (Movie) values ('Kismet');
insert into MOCK_DATA (Movie) values ('Short Film About Killing, A (Krótki film o zabijaniu)');
insert into MOCK_DATA (Movie) values ('Muppet Christmas Carol, The');
insert into MOCK_DATA (Movie) values ('Pathology');
insert into MOCK_DATA (Movie) values ('Mallrats');
insert into MOCK_DATA (Movie) values ('Blossoming of Maximo Oliveros, The (Ang pagdadalaga ni Maximo Oliveros)');
insert into MOCK_DATA (Movie) values ('Cinderella III: A Twist in Time');
insert into MOCK_DATA (Movie) values ('All Quiet on the Western Front');
insert into MOCK_DATA (Movie) values ('Secret Adventures of Gustave Klopp, The (Narco)');
insert into MOCK_DATA (Movie) values ('Penitentiary');
insert into MOCK_DATA (Movie) values ('Comanche Station');
insert into MOCK_DATA (Movie) values ('Roger & Me');
insert into MOCK_DATA (Movie) values ('Alien Autopsy');
insert into MOCK_DATA (Movie) values ('Thrushes Are Still Singing, The (Ta kourelia tragoudane akoma...)');
insert into MOCK_DATA (Movie) values ('Haunted, The');
insert into MOCK_DATA (Movie) values ('Real Steel');
insert into MOCK_DATA (Movie) values ('Ultimate Avengers');
insert into MOCK_DATA (Movie) values ('Bill Burr: I''m Sorry You Feel That Way');
insert into MOCK_DATA (Movie) values ('Straw Dogs');
insert into MOCK_DATA (Movie) values ('Death Wish 5: The Face of Death');
insert into MOCK_DATA (Movie) values ('Red Corner');
insert into MOCK_DATA (Movie) values ('Graveyard of Honor (Shin jingi no hakaba)');
insert into MOCK_DATA (Movie) values ('Tür, Die (Door, The)');
insert into MOCK_DATA (Movie) values ('Sugar & Spice');
insert into MOCK_DATA (Movie) values ('Cry_Wolf (a.k.a. Cry Wolf)');
insert into MOCK_DATA (Movie) values ('Frida');
insert into MOCK_DATA (Movie) values ('Went the Day Well?');
insert into MOCK_DATA (Movie) values ('Swiss Family Robinson');
insert into MOCK_DATA (Movie) values ('Beastie Boys: Sabotage');
insert into MOCK_DATA (Movie) values ('Simpsons Movie, The');
insert into MOCK_DATA (Movie) values ('Hellion');
insert into MOCK_DATA (Movie) values ('Drama/Mex');
insert into MOCK_DATA (Movie) values ('Lavatory Lovestory (Ubornaya istoriya - lyubovnaya istoriya)');
insert into MOCK_DATA (Movie) values ('Sitcom');
insert into MOCK_DATA (Movie) values ('National Lampoon''s Senior Trip');
insert into MOCK_DATA (Movie) values ('Nordkraft');
insert into MOCK_DATA (Movie) values ('Phase 7');
insert into MOCK_DATA (Movie) values ('Everything You Always Wanted to Know About Sex * But Were Afraid to Ask');
insert into MOCK_DATA (Movie) values ('Someone Like You');
insert into MOCK_DATA (Movie) values ('Wing Commander');
insert into MOCK_DATA (Movie) values ('Hard Luck');
insert into MOCK_DATA (Movie) values ('Tetsuo, the Ironman (Tetsuo)');
insert into MOCK_DATA (Movie) values ('How to Deal');
insert into MOCK_DATA (Movie) values ('Hitchhiker''s Guide to the Galaxy, The');
insert into MOCK_DATA (Movie) values ('I Even Met Happy Gypsies (Skupljaci perja)');
insert into MOCK_DATA (Movie) values ('Spring is Here');
insert into MOCK_DATA (Movie) values ('Blind Massage (Tui na)');
insert into MOCK_DATA (Movie) values ('Before Flying Back to Earth (Pries parskrendant i zeme)');
insert into MOCK_DATA (Movie) values ('Mount Head (Atama yama)');
insert into MOCK_DATA (Movie) values ('Fire-Eater (Tulennielijä)');
insert into MOCK_DATA (Movie) values ('Tour De Force (Hin und weg)');
insert into MOCK_DATA (Movie) values ('Foul King, The (Banchikwang)');
insert into MOCK_DATA (Movie) values ('Choose');
insert into MOCK_DATA (Movie) values ('New World, The');
insert into MOCK_DATA (Movie) values ('V/H/S/2');
insert into MOCK_DATA (Movie) values ('We Always Lie to Strangers');
insert into MOCK_DATA (Movie) values ('Dampfnudelblues');
insert into MOCK_DATA (Movie) values ('Jane Eyre');
insert into MOCK_DATA (Movie) values ('Angele');
insert into MOCK_DATA (Movie) values ('Kawasaki''s Rose ');
insert into MOCK_DATA (Movie) values ('May Fools (Milou en mai)');
insert into MOCK_DATA (Movie) values ('Space Chimps');
insert into MOCK_DATA (Movie) values ('Begin Again');
insert into MOCK_DATA (Movie) values ('Hit and Runway');
insert into MOCK_DATA (Movie) values ('Shadrach');
insert into MOCK_DATA (Movie) values ('Shanghai');
insert into MOCK_DATA (Movie) values ('Down by Law');
insert into MOCK_DATA (Movie) values ('Skies Above the Landscape (Nebo iznad krajolika)');
insert into MOCK_DATA (Movie) values ('Goodbye to Language 3D');
insert into MOCK_DATA (Movie) values ('Eat');
insert into MOCK_DATA (Movie) values ('Aziz Ansari: Intimate Moments for a Sensual Evening');
insert into MOCK_DATA (Movie) values ('Miracles - Mr. Canton and Lady Rose');
insert into MOCK_DATA (Movie) values ('Art of the Steal, The');
insert into MOCK_DATA (Movie) values ('Why Stop Now');
insert into MOCK_DATA (Movie) values ('Slammin'' Salmon, The');
insert into MOCK_DATA (Movie) values ('Friday the 13th Part IV: The Final Chapter');
insert into MOCK_DATA (Movie) values ('Shake Hands with the Devil');
insert into MOCK_DATA (Movie) values ('Mystic River');
insert into MOCK_DATA (Movie) values ('Pickle, The');
insert into MOCK_DATA (Movie) values ('Parking Lot Movie, The');
insert into MOCK_DATA (Movie) values ('Road to Rio');
insert into MOCK_DATA (Movie) values ('Man Called Gannon, A');
insert into MOCK_DATA (Movie) values ('Trailer Park Jesus');
insert into MOCK_DATA (Movie) values ('Charlie Chan at the Opera');
insert into MOCK_DATA (Movie) values ('Betty Blue (37°2 le matin)');
insert into MOCK_DATA (Movie) values ('Blown Away');
insert into MOCK_DATA (Movie) values ('Killer Shrews, The');
insert into MOCK_DATA (Movie) values ('Natural, The');
insert into MOCK_DATA (Movie) values ('King - Jari Litmanen, The (Kuningas Litmanen)');
insert into MOCK_DATA (Movie) values ('Antonio das Mortes (O Dragão da Maldade contra o Santo Guerreiro)');
insert into MOCK_DATA (Movie) values ('Billy Elliot');
insert into MOCK_DATA (Movie) values ('Magnificent Seven, The');
insert into MOCK_DATA (Movie) values ('Music From Another Room');
insert into MOCK_DATA (Movie) values ('Pill, The');
insert into MOCK_DATA (Movie) values ('Pride and Prejudice');
insert into MOCK_DATA (Movie) values ('Shirin');
insert into MOCK_DATA (Movie) values ('Place Called Chiapas, A');
insert into MOCK_DATA (Movie) values ('Love at Large');
insert into MOCK_DATA (Movie) values ('Jack and the Beanstalk');
insert into MOCK_DATA (Movie) values ('So Long Letty');
insert into MOCK_DATA (Movie) values ('Julie & Julia');
insert into MOCK_DATA (Movie) values ('Submarine X-1');
insert into MOCK_DATA (Movie) values ('Grabbers');
insert into MOCK_DATA (Movie) values ('Sophie''s World (Sofies verden)');
insert into MOCK_DATA (Movie) values ('Rewrite, The');
insert into MOCK_DATA (Movie) values ('Let''s Scare Jessica to Death');
insert into MOCK_DATA (Movie) values ('Whoopi Goldberg Presents Moms Mabley');
insert into MOCK_DATA (Movie) values ('All the Way Home');
insert into MOCK_DATA (Movie) values ('Reincarnation of Peter Proud, The');
insert into MOCK_DATA (Movie) values ('Christmas in July');
insert into MOCK_DATA (Movie) values ('Wrath of God, The');
insert into MOCK_DATA (Movie) values ('Rancho Notorious');
insert into MOCK_DATA (Movie) values ('Charley Varrick');
insert into MOCK_DATA (Movie) values ('Mendy: A Question of Faith');
insert into MOCK_DATA (Movie) values ('Laramie Project, The');
insert into MOCK_DATA (Movie) values ('Spiritual Kung Fu (Quan jing)');
insert into MOCK_DATA (Movie) values ('Ballad of the Paper Balloons (a.k.a. Humanity and Paper Balloons) (Ninjô kami fûsen)');
insert into MOCK_DATA (Movie) values ('Last Man on Earth, The (Ultimo uomo della Terra, L'')');
insert into MOCK_DATA (Movie) values ('Teen Beach Movie');
insert into MOCK_DATA (Movie) values ('Game Over');
insert into MOCK_DATA (Movie) values ('It''s Kind of a Funny Story');
insert into MOCK_DATA (Movie) values ('Most Dangerous Game, The');
insert into MOCK_DATA (Movie) values ('Begin Again');
insert into MOCK_DATA (Movie) values ('Arthur Newman');
insert into MOCK_DATA (Movie) values ('Roseland');
insert into MOCK_DATA (Movie) values ('Nanny Diaries, The');
insert into MOCK_DATA (Movie) values ('As We Were Dreaming');
insert into MOCK_DATA (Movie) values ('Amazon Jack 2: The Movie Star (a.k.a. Hugo the Movie Star) (Jungledyret 2 - den store filmhelt)');
insert into MOCK_DATA (Movie) values ('Samurai Banners (Fûrin kazan)');
insert into MOCK_DATA (Movie) values ('The White Sister');
insert into MOCK_DATA (Movie) values ('Who Is Cletis Tout?');
insert into MOCK_DATA (Movie) values ('Incredible Shrinking Woman, The');
insert into MOCK_DATA (Movie) values ('Curtis''s Charm');
insert into MOCK_DATA (Movie) values ('Assassination Bureau, The');
insert into MOCK_DATA (Movie) values ('This Girl''s Life');
insert into MOCK_DATA (Movie) values ('Hell Comes to Frogtown');
insert into MOCK_DATA (Movie) values ('Mona Lisa Smile');
insert into MOCK_DATA (Movie) values ('Doctor X');
insert into MOCK_DATA (Movie) values ('Boys from Fengkuei, The (Feng gui lai de ren)');
insert into MOCK_DATA (Movie) values ('Last Warrior, The (Last Patrol, The)');
insert into MOCK_DATA (Movie) values ('Earth Entranced (Terra em Transe)');
insert into MOCK_DATA (Movie) values ('Mysterious Skin');
insert into MOCK_DATA (Movie) values ('Late Marriage (Hatuna Meuheret)');
insert into MOCK_DATA (Movie) values ('Caught');
insert into MOCK_DATA (Movie) values ('City of Women, The (Città delle donne, La)');
insert into MOCK_DATA (Movie) values ('Temptress, The');
insert into MOCK_DATA (Movie) values ('Firecreek');
insert into MOCK_DATA (Movie) values ('Kumail Nanjiani: Beta Male ');
insert into MOCK_DATA (Movie) values ('Up in the Wind');
insert into MOCK_DATA (Movie) values ('Being Elmo: A Puppeteer''s Journey');
insert into MOCK_DATA (Movie) values ('Singapore Sling (Singapore sling: O anthropos pou agapise ena ptoma)');
insert into MOCK_DATA (Movie) values ('American Dream');
insert into MOCK_DATA (Movie) values ('10 Items or Less');
insert into MOCK_DATA (Movie) values ('The Good Son');
insert into MOCK_DATA (Movie) values ('Moulin Rouge');
insert into MOCK_DATA (Movie) values ('Sign of Four, The');
insert into MOCK_DATA (Movie) values ('Little Murders');
insert into MOCK_DATA (Movie) values ('Made in Heaven');
insert into MOCK_DATA (Movie) values ('Shadowlands');
insert into MOCK_DATA (Movie) values ('In the Mirror of Maya Deren (Im Spiegel der Maya Deren)');
insert into MOCK_DATA (Movie) values ('Love Guru, The');
insert into MOCK_DATA (Movie) values ('36 fillette');
insert into MOCK_DATA (Movie) values ('Ranma ½: Nihao My Concubine (Ranma ½: Kessen Tôgenkyô! Hanayome o torimodose!!)');
insert into MOCK_DATA (Movie) values ('Safety Not Guaranteed');
insert into MOCK_DATA (Movie) values ('Go Tigers!');
insert into MOCK_DATA (Movie) values ('In Old California');
insert into MOCK_DATA (Movie) values ('Take Care of Your Scarf, Tatiana (Pidä huivista kiinni, Tatjana)');
insert into MOCK_DATA (Movie) values ('End of the Game (Der Richter und sein Henker)');
insert into MOCK_DATA (Movie) values ('Yellowbeard');
insert into MOCK_DATA (Movie) values ('Blood for Dracula (Andy Warhol''s Dracula)');
insert into MOCK_DATA (Movie) values ('Unfinished Life, An');
insert into MOCK_DATA (Movie) values ('Lost Son, The');
insert into MOCK_DATA (Movie) values ('Banishment, The (Izgnanie)');
insert into MOCK_DATA (Movie) values ('Frankie and Johnny');
insert into MOCK_DATA (Movie) values ('Kansas Raiders');
insert into MOCK_DATA (Movie) values ('Street Fighter: The Legend of Chun-Li');
insert into MOCK_DATA (Movie) values ('Sightseers');
insert into MOCK_DATA (Movie) values ('Missionary');
insert into MOCK_DATA (Movie) values ('Destination Moon');
insert into MOCK_DATA (Movie) values ('Jauja');
insert into MOCK_DATA (Movie) values ('Long Kiss Goodnight, The');
insert into MOCK_DATA (Movie) values ('Mr Hublot');
insert into MOCK_DATA (Movie) values ('Happy Together');
insert into MOCK_DATA (Movie) values ('Miss March');
insert into MOCK_DATA (Movie) values ('Sinbad: Legend of the Seven Seas');
insert into MOCK_DATA (Movie) values ('Hôtel des Invalides');
insert into MOCK_DATA (Movie) values ('Liquidator, The');
insert into MOCK_DATA (Movie) values ('Salmon Fishing in the Yemen');
insert into MOCK_DATA (Movie) values ('Blindness');
insert into MOCK_DATA (Movie) values ('Love''s Enduring Promise');
insert into MOCK_DATA (Movie) values ('Daisy Miller');
insert into MOCK_DATA (Movie) values ('The World Forgotten');
insert into MOCK_DATA (Movie) values ('Fade To Black');
insert into MOCK_DATA (Movie) values ('Turtles Can Fly (Lakposhtha hâm parvaz mikonand)');
insert into MOCK_DATA (Movie) values ('Africa addio');
insert into MOCK_DATA (Movie) values ('I Am the Law');
insert into MOCK_DATA (Movie) values ('Preacher, The (De dominee)');
insert into MOCK_DATA (Movie) values ('Blue Collar Comedy Tour: The Movie');
insert into MOCK_DATA (Movie) values ('Diana');
insert into MOCK_DATA (Movie) values ('Crank: High Voltage');
insert into MOCK_DATA (Movie) values ('Piter FM');
insert into MOCK_DATA (Movie) values ('Donkey Punch');
insert into MOCK_DATA (Movie) values ('Not One Less (Yi ge dou bu neng shao)');
insert into MOCK_DATA (Movie) values ('American Adobo');
insert into MOCK_DATA (Movie) values ('League of Ordinary Gentlemen, A');
insert into MOCK_DATA (Movie) values ('C.H.U.D. II - Bud the Chud');
insert into MOCK_DATA (Movie) values ('Man with No Shadow, The (Homme sans ombre, L'')');
insert into MOCK_DATA (Movie) values ('Lunch Break');
insert into MOCK_DATA (Movie) values ('Man''s Job (Miehen työ)');
insert into MOCK_DATA (Movie) values ('Mimic');
insert into MOCK_DATA (Movie) values ('Troubled Water (DeUsynlige)');
insert into MOCK_DATA (Movie) values ('Neds');
insert into MOCK_DATA (Movie) values ('Dracula''s Daughter');
insert into MOCK_DATA (Movie) values ('Step Up 2 the Streets');
insert into MOCK_DATA (Movie) values ('Scooby-Doo! Camp Scare');
insert into MOCK_DATA (Movie) values ('Tales of Ordinary Madness (Storie di Ordinaria Follia)');
insert into MOCK_DATA (Movie) values ('Ninth Gate, The');
insert into MOCK_DATA (Movie) values ('Paradise: Love');
insert into MOCK_DATA (Movie) values ('Alice in Wonderland');
insert into MOCK_DATA (Movie) values ('Dolls and Angels');
insert into MOCK_DATA (Movie) values ('Nymph');
insert into MOCK_DATA (Movie) values ('Des fleurs pour Algernon');
insert into MOCK_DATA (Movie) values ('Night Passage');
insert into MOCK_DATA (Movie) values ('The Kiss');
insert into MOCK_DATA (Movie) values ('Entertainer, The');
insert into MOCK_DATA (Movie) values ('Harry Potter and the Chamber of Secrets');
insert into MOCK_DATA (Movie) values ('Torn');
insert into MOCK_DATA (Movie) values ('Porco Rosso (Crimson Pig) (Kurenai no buta)');
insert into MOCK_DATA (Movie) values ('Stitch! The Movie');
insert into MOCK_DATA (Movie) values ('Days of Grace (Días de gracia) ');
insert into MOCK_DATA (Movie) values ('Dirty Pictures');
insert into MOCK_DATA (Movie) values ('Killers');
insert into MOCK_DATA (Movie) values ('Looker');
insert into MOCK_DATA (Movie) values ('Lucie Aubrac');
insert into MOCK_DATA (Movie) values ('Kelly''s Heroes');
insert into MOCK_DATA (Movie) values ('Phantom Pain');
insert into MOCK_DATA (Movie) values ('Song of the Little Road (Pather Panchali)');
insert into MOCK_DATA (Movie) values ('Mechanic, The');
insert into MOCK_DATA (Movie) values ('Nanayo (Nanayomachi)');
insert into MOCK_DATA (Movie) values ('Snowballs');
insert into MOCK_DATA (Movie) values ('Escapist, The');
insert into MOCK_DATA (Movie) values ('Four Days of Naples, The (Le quattro giornate di Napoli)');
insert into MOCK_DATA (Movie) values ('Moving Alan');
insert into MOCK_DATA (Movie) values ('Mysterious Island');
insert into MOCK_DATA (Movie) values ('The Land Before Time VII: The Stone of Cold Fire');
insert into MOCK_DATA (Movie) values ('El Dorado');
insert into MOCK_DATA (Movie) values ('My Wrongs 8245-8249 and 117');
insert into MOCK_DATA (Movie) values ('Golden Bowl, The');
insert into MOCK_DATA (Movie) values ('V2: Dead Angel (Vares 2 - Jäätynyt Enkeli)');
insert into MOCK_DATA (Movie) values ('Thurgood');
insert into MOCK_DATA (Movie) values ('Rising Place, The');
insert into MOCK_DATA (Movie) values ('Lone Wolf and Cub: Baby Cart in the Land of Demons (Kozure Ôkami: Meifumadô)');
insert into MOCK_DATA (Movie) values ('Marihuana');
insert into MOCK_DATA (Movie) values ('Son of the Pink Panther');
insert into MOCK_DATA (Movie) values ('Abandoned, The');
insert into MOCK_DATA (Movie) values ('Wagon Master');
insert into MOCK_DATA (Movie) values ('Murmur of the Heart (Le souffle au coeur)');
insert into MOCK_DATA (Movie) values ('Goodfellas');
insert into MOCK_DATA (Movie) values ('Wake in Fright');
insert into MOCK_DATA (Movie) values ('Summer Wishes, Winter Dreams');
insert into MOCK_DATA (Movie) values ('Computer Chess');
insert into MOCK_DATA (Movie) values ('Murder!');
insert into MOCK_DATA (Movie) values ('Hearty Paws');
insert into MOCK_DATA (Movie) values ('Necessary Roughness');
insert into MOCK_DATA (Movie) values ('Any Questions for Ben?');
insert into MOCK_DATA (Movie) values ('1612: Khroniki smutnogo vremeni');
insert into MOCK_DATA (Movie) values ('Beyond Silence (Jenseits der Stille)');
insert into MOCK_DATA (Movie) values ('This Time Around');
insert into MOCK_DATA (Movie) values ('Mirror Mirror');
insert into MOCK_DATA (Movie) values ('Live Free or Die');
insert into MOCK_DATA (Movie) values ('Toughest Man in the World, The');
insert into MOCK_DATA (Movie) values ('Café de Flore');
insert into MOCK_DATA (Movie) values ('Gainsbourg (Vie Héroïque)');
insert into MOCK_DATA (Movie) values ('Bushwhacked');
insert into MOCK_DATA (Movie) values ('Little Thief, The (La petite voleuse)');
insert into MOCK_DATA (Movie) values ('Daens');
insert into MOCK_DATA (Movie) values ('Patsy, The');
insert into MOCK_DATA (Movie) values ('Human Trafficking');
insert into MOCK_DATA (Movie) values ('Pal Joey');
insert into MOCK_DATA (Movie) values ('Under the Skin');
insert into MOCK_DATA (Movie) values ('Desperados, The');
insert into MOCK_DATA (Movie) values ('Firefox');
insert into MOCK_DATA (Movie) values ('Nobody Wants the Night');
insert into MOCK_DATA (Movie) values ('Chato''s Land');
insert into MOCK_DATA (Movie) values ('Out On A Limb');
insert into MOCK_DATA (Movie) values ('Liebestraum');
insert into MOCK_DATA (Movie) values ('Class of 1999 II: The Substitute');
insert into MOCK_DATA (Movie) values ('Parenti serpenti');
insert into MOCK_DATA (Movie) values ('Torrente, el brazo tonto de la ley');
insert into MOCK_DATA (Movie) values ('It''s the Great Pumpkin, Charlie Brown');
insert into MOCK_DATA (Movie) values ('Crazy Love');
insert into MOCK_DATA (Movie) values ('American Crude');
insert into MOCK_DATA (Movie) values ('Cargo');
insert into MOCK_DATA (Movie) values ('Nine Lives');
insert into MOCK_DATA (Movie) values ('Dark Side of the Heart, The (Lado oscuro del corazón, El)');
insert into MOCK_DATA (Movie) values ('Four Brothers');
insert into MOCK_DATA (Movie) values ('San Antonio');
insert into MOCK_DATA (Movie) values ('Sunchaser, The');
insert into MOCK_DATA (Movie) values ('Sound Barrier, The');
insert into MOCK_DATA (Movie) values ('Yours, Mine and Ours');
insert into MOCK_DATA (Movie) values ('Shaolin Soccer (Siu lam juk kau)');
insert into MOCK_DATA (Movie) values ('Inheritance, The (Karami-ai)');
insert into MOCK_DATA (Movie) values ('Home');
insert into MOCK_DATA (Movie) values ('Knights of the Round Table');
insert into MOCK_DATA (Movie) values ('Shivers (They Came from Within)');
insert into MOCK_DATA (Movie) values ('Abigail''s Party');
insert into MOCK_DATA (Movie) values ('Sunes sommar');
insert into MOCK_DATA (Movie) values ('Show People');
insert into MOCK_DATA (Movie) values ('Knock Off');
insert into MOCK_DATA (Movie) values ('Black Tar Heroin: The Dark End of the Street');
insert into MOCK_DATA (Movie) values ('Maid, The (Nana, La)');
insert into MOCK_DATA (Movie) values ('Puzzlehead');
insert into MOCK_DATA (Movie) values ('Flicka');
insert into MOCK_DATA (Movie) values ('Of Unknown Origin');
insert into MOCK_DATA (Movie) values ('Lightning Bolt: The Power of Salad');
insert into MOCK_DATA (Movie) values ('Scooby-Doo 2: Monsters Unleashed');
insert into MOCK_DATA (Movie) values ('My Winnipeg');
insert into MOCK_DATA (Movie) values ('Burial Ground (a.k.a. Zombie Horror) (a.k.a. Zombie 3) (Notti del Terrore, Le)');
insert into MOCK_DATA (Movie) values ('Traveller');
insert into MOCK_DATA (Movie) values ('Wizards');
insert into MOCK_DATA (Movie) values ('Gremlins 2: The New Batch');
insert into MOCK_DATA (Movie) values ('Bedtime Story');
insert into MOCK_DATA (Movie) values ('Honest Man: The Life of R. Budd Dwyer');
insert into MOCK_DATA (Movie) values ('Female Prisoner #701: Scorpion (Joshuu 701-gô: Sasori)');
insert into MOCK_DATA (Movie) values ('Dinner with Friends');
insert into MOCK_DATA (Movie) values ('Pyramid of Triboulet, The (La pyramide de Triboulet)');
insert into MOCK_DATA (Movie) values ('Diplomatic Siege');
insert into MOCK_DATA (Movie) values ('Mothlight');
insert into MOCK_DATA (Movie) values ('Lodger, The');
insert into MOCK_DATA (Movie) values ('Buddies (Colegas)');
insert into MOCK_DATA (Movie) values ('The Shadow of the Eagle');
insert into MOCK_DATA (Movie) values ('Hider in the House');
insert into MOCK_DATA (Movie) values ('Summer of Blood');
insert into MOCK_DATA (Movie) values ('Don Verdean');
insert into MOCK_DATA (Movie) values ('Ron Clark Story, The');
insert into MOCK_DATA (Movie) values ('Alone in the Dark');
insert into MOCK_DATA (Movie) values ('Big Fix, The');
insert into MOCK_DATA (Movie) values ('City of Sadness, A (Bei qing cheng shi)');
insert into MOCK_DATA (Movie) values ('Invaders from Mars');
insert into MOCK_DATA (Movie) values ('Who''s Afraid of Virginia Woolf?');
insert into MOCK_DATA (Movie) values ('In Your Dreams (Dans tes rêves)');
insert into MOCK_DATA (Movie) values ('Wrestler, The (Painija)');
insert into MOCK_DATA (Movie) values ('Fist of the North Star');
insert into MOCK_DATA (Movie) values ('Splice');
insert into MOCK_DATA (Movie) values ('Sister Street Fighter (Onna hissatsu ken)');
insert into MOCK_DATA (Movie) values ('Basara: Princess Goh');
insert into MOCK_DATA (Movie) values ('Great Ziegfeld, The');
insert into MOCK_DATA (Movie) values ('Shark Tale');
insert into MOCK_DATA (Movie) values ('Human Scale, The');
insert into MOCK_DATA (Movie) values ('Tatie Danielle');
insert into MOCK_DATA (Movie) values ('Simpatico');
insert into MOCK_DATA (Movie) values ('Radio Free Albemuth');
insert into MOCK_DATA (Movie) values ('Staten Island');
insert into MOCK_DATA (Movie) values ('Alien Trespass');
insert into MOCK_DATA (Movie) values ('Other Dream Team, The');
insert into MOCK_DATA (Movie) values ('Max Manus');
insert into MOCK_DATA (Movie) values ('Constant Gardener, The');
insert into MOCK_DATA (Movie) values ('Hell and High Water');
insert into MOCK_DATA (Movie) values ('Moonshot');
insert into MOCK_DATA (Movie) values ('Human Touch');
insert into MOCK_DATA (Movie) values ('Julie Johnson');
insert into MOCK_DATA (Movie) values ('Girl, Interrupted');
insert into MOCK_DATA (Movie) values ('Wise Guys, The (Les grandes gueules)');
insert into MOCK_DATA (Movie) values ('Chair, The');
insert into MOCK_DATA (Movie) values ('Khumba');
insert into MOCK_DATA (Movie) values ('Little Criminals');
insert into MOCK_DATA (Movie) values ('Wildcats');
insert into MOCK_DATA (Movie) values ('Pirates');
insert into MOCK_DATA (Movie) values ('Agony (a.k.a. Rasputin) (Agoniya)');
insert into MOCK_DATA (Movie) values ('Man Vanishes, A (Ningen Johatsu)');
insert into MOCK_DATA (Movie) values ('Snatch');
insert into MOCK_DATA (Movie) values ('Svengali');
insert into MOCK_DATA (Movie) values ('Parked');
insert into MOCK_DATA (Movie) values ('Hit List, The');
insert into MOCK_DATA (Movie) values ('Leprechaun 3');
insert into MOCK_DATA (Movie) values ('Scary Movie 3');
insert into MOCK_DATA (Movie) values ('Amadeus');
insert into MOCK_DATA (Movie) values ('Family Game, The (Kazoku gêmu)');
insert into MOCK_DATA (Movie) values ('City of Ghosts');
insert into MOCK_DATA (Movie) values ('Virtuosity');
insert into MOCK_DATA (Movie) values ('One Trick Pony');
insert into MOCK_DATA (Movie) values ('Older Brother, Younger Sister (Ani imôto)');
insert into MOCK_DATA (Movie) values ('Lilian''s Story');
insert into MOCK_DATA (Movie) values ('Forever Hardcore: The Documentary');
insert into MOCK_DATA (Movie) values ('Naughty Girl');
insert into MOCK_DATA (Movie) values ('Go West');
insert into MOCK_DATA (Movie) values ('Kill Your Darlings');
insert into MOCK_DATA (Movie) values ('Visitors');
insert into MOCK_DATA (Movie) values ('Enter Arsene Lupin');
insert into MOCK_DATA (Movie) values ('Orphan');
insert into MOCK_DATA (Movie) values ('Roberta');
insert into MOCK_DATA (Movie) values ('Rapture-Palooza');
insert into MOCK_DATA (Movie) values ('5,000 Fingers of Dr. T, The');
insert into MOCK_DATA (Movie) values ('I''m Going Home (Je rentre à la maison)');
insert into MOCK_DATA (Movie) values ('Nô');
insert into MOCK_DATA (Movie) values ('Down and Out with the Dolls');
insert into MOCK_DATA (Movie) values ('Disgrace');
insert into MOCK_DATA (Movie) values ('David Copperfield');
insert into MOCK_DATA (Movie) values ('Still Crazy');
insert into MOCK_DATA (Movie) values ('Pahat pojat');
insert into MOCK_DATA (Movie) values ('Beautiful Troublemaker, The (La belle noiseuse)');
insert into MOCK_DATA (Movie) values ('Nymphomaniac: Volume II');
insert into MOCK_DATA (Movie) values ('Hedd Wyn');
insert into MOCK_DATA (Movie) values ('Burn After Reading');
insert into MOCK_DATA (Movie) values ('Even the Rain (También la lluvia)');
insert into MOCK_DATA (Movie) values ('Love unto Death (L''amour a mort)');
insert into MOCK_DATA (Movie) values ('Renoir');
insert into MOCK_DATA (Movie) values ('Lucky Break (a.k.a. Paperback Romance)');
insert into MOCK_DATA (Movie) values ('Story of Louis Pasteur, The');
insert into MOCK_DATA (Movie) values ('Legend of Hercules, The');
insert into MOCK_DATA (Movie) values ('Born Wild');
insert into MOCK_DATA (Movie) values ('Birds, The');
insert into MOCK_DATA (Movie) values ('Up in the Air');
insert into MOCK_DATA (Movie) values ('Command Performance');
insert into MOCK_DATA (Movie) values ('Escanaba in da Moonlight');
insert into MOCK_DATA (Movie) values ('Carandiru');
insert into MOCK_DATA (Movie) values ('In This Our Life');
insert into MOCK_DATA (Movie) values ('Bring It On Again');
insert into MOCK_DATA (Movie) values ('Hellraiser: Bloodline');
insert into MOCK_DATA (Movie) values ('Blackout');
insert into MOCK_DATA (Movie) values ('Night Visitor, The');
insert into MOCK_DATA (Movie) values ('All the Boys Love Mandy Lane');
insert into MOCK_DATA (Movie) values ('In Tranzit');
insert into MOCK_DATA (Movie) values ('Mutantes');
insert into MOCK_DATA (Movie) values ('India Song');
insert into MOCK_DATA (Movie) values ('I Went Down');
insert into MOCK_DATA (Movie) values ('Children of a Lesser God');
insert into MOCK_DATA (Movie) values ('Give ''em Hell, Malone');
insert into MOCK_DATA (Movie) values ('Hardware');
insert into MOCK_DATA (Movie) values ('Prom Night in Mississippi');
insert into MOCK_DATA (Movie) values ('Painting Sellers, The (Taulukauppiaat)');
insert into MOCK_DATA (Movie) values ('Agnes Browne');
insert into MOCK_DATA (Movie) values ('Dirty Girl');
insert into MOCK_DATA (Movie) values ('Deserter (Dezertir)');
insert into MOCK_DATA (Movie) values ('Sebastian Maniscalco: What''s Wrong with People?');
insert into MOCK_DATA (Movie) values ('Disaster L.A.');
insert into MOCK_DATA (Movie) values ('Birds of America');
insert into MOCK_DATA (Movie) values ('M');
insert into MOCK_DATA (Movie) values ('Double Take');
insert into MOCK_DATA (Movie) values ('Surrogates');
insert into MOCK_DATA (Movie) values ('The Italian Connection');
insert into MOCK_DATA (Movie) values ('My Mother''s Courage (Mutters Courage)');
insert into MOCK_DATA (Movie) values ('Sweepers');
insert into MOCK_DATA (Movie) values ('Foxfire');
insert into MOCK_DATA (Movie) values ('Jekyll & Hyde');
insert into MOCK_DATA (Movie) values ('Stepford Wives, The');
insert into MOCK_DATA (Movie) values ('Belphecor: Curse of the Mummy (Belphégor - Le fantôme du Louvre)');
insert into MOCK_DATA (Movie) values ('Touching the Void');
insert into MOCK_DATA (Movie) values ('Napoleon');
insert into MOCK_DATA (Movie) values ('Tracy Morgan: Black and Blue');
insert into MOCK_DATA (Movie) values ('Visitors, The');
insert into MOCK_DATA (Movie) values ('Happy Time, The');
insert into MOCK_DATA (Movie) values ('Furry Vengeance');
insert into MOCK_DATA (Movie) values ('Always Tell Your Wife');
insert into MOCK_DATA (Movie) values ('Hunted City');
insert into MOCK_DATA (Movie) values ('Beast from 20,000 Fathoms, The');
insert into MOCK_DATA (Movie) values ('Living in Oblivion');
insert into MOCK_DATA (Movie) values ('Sirocco');
insert into MOCK_DATA (Movie) values ('Brick Mansions');
insert into MOCK_DATA (Movie) values ('Geography Club');
insert into MOCK_DATA (Movie) values ('Heart of America');
insert into MOCK_DATA (Movie) values ('Beverly Hills Ninja');
insert into MOCK_DATA (Movie) values ('Fanatics (Kulman pojat)');
insert into MOCK_DATA (Movie) values ('Topo, El');
insert into MOCK_DATA (Movie) values ('Paris by Night');
insert into MOCK_DATA (Movie) values ('Badlands');
insert into MOCK_DATA (Movie) values ('Out On A Limb');
insert into MOCK_DATA (Movie) values ('Farewell to Arms, A');
insert into MOCK_DATA (Movie) values ('Legend of the Black Scorpion (a.k.a. The Banquet) (Ye yan)');
insert into MOCK_DATA (Movie) values ('Mighty Heart, A');
insert into MOCK_DATA (Movie) values ('Miguel and William (Miguel y William)');
insert into MOCK_DATA (Movie) values ('Wicked Little Things');
insert into MOCK_DATA (Movie) values ('Banshee Chapter, The');
insert into MOCK_DATA (Movie) values ('F/X');
insert into MOCK_DATA (Movie) values ('Appointment in Tokyo');
insert into MOCK_DATA (Movie) values ('Riders of the Purple Sage');
insert into MOCK_DATA (Movie) values ('Unconditional');
insert into MOCK_DATA (Movie) values ('Season of Monsters (Szörnyek évadja) ');
insert into MOCK_DATA (Movie) values ('Lover''s Knot');
insert into MOCK_DATA (Movie) values ('Divergent');
insert into MOCK_DATA (Movie) values ('S.O.B.');
insert into MOCK_DATA (Movie) values ('Teenage Dirtbag');
insert into MOCK_DATA (Movie) values ('John Doe: Vigilante');
insert into MOCK_DATA (Movie) values ('Blind (Beul-la-in-deu)');
insert into MOCK_DATA (Movie) values ('Nekromantik');
insert into MOCK_DATA (Movie) values ('Deliverance Creek');
insert into MOCK_DATA (Movie) values ('Gentlemen of Fortune (Dzhentlmeny udachi)');
insert into MOCK_DATA (Movie) values ('Q');
insert into MOCK_DATA (Movie) values ('False Trail (Jägarna 2)');
insert into MOCK_DATA (Movie) values ('Bait');
insert into MOCK_DATA (Movie) values ('Fireworks Wednesday (Chaharshanbe-soori)');
insert into MOCK_DATA (Movie) values ('Long and Short of It, The');
insert into MOCK_DATA (Movie) values ('Pyramid, The');
insert into MOCK_DATA (Movie) values ('Paper Chase, The');
insert into MOCK_DATA (Movie) values ('Forbidden Planet');
insert into MOCK_DATA (Movie) values ('Island of Dr. Moreau, The');
insert into MOCK_DATA (Movie) values ('Thieves, The (Dodookdeul)');
insert into MOCK_DATA (Movie) values ('Last Days of Pompeii, The (Gli ultimi giorni di Pompeii)');
insert into MOCK_DATA (Movie) values ('Yolki');
insert into MOCK_DATA (Movie) values ('Sweet Smell of Success');
insert into MOCK_DATA (Movie) values ('Susan Lenox (Her Fall and Rise)');
insert into MOCK_DATA (Movie) values ('Howards End');
insert into MOCK_DATA (Movie) values ('Last Run, The');
insert into MOCK_DATA (Movie) values ('Maid in Manhattan');
insert into MOCK_DATA (Movie) values ('Mike Birbiglia: My Girlfriend''s Boyfriend');
insert into MOCK_DATA (Movie) values ('Anchorman: The Legend of Ron Burgundy');
insert into MOCK_DATA (Movie) values ('Music Man, The');
insert into MOCK_DATA (Movie) values ('Crime Zone');
insert into MOCK_DATA (Movie) values ('Cabin Boy');
insert into MOCK_DATA (Movie) values ('Henry IV, Part I (First Part of King Henry the Fourth, with the Life and Death of Henry Surnamed Hotspur, The)');
insert into MOCK_DATA (Movie) values ('Institute, The');
insert into MOCK_DATA (Movie) values ('Lenny Bruce: Swear to Tell the Truth');
insert into MOCK_DATA (Movie) values ('Zero');
insert into MOCK_DATA (Movie) values ('Crooked Arrows');
insert into MOCK_DATA (Movie) values ('Billion Dollar Brain');
insert into MOCK_DATA (Movie) values ('Plato''s Academy');
insert into MOCK_DATA (Movie) values ('Good Man in Africa, A');
insert into MOCK_DATA (Movie) values ('So Much So Fast');
insert into MOCK_DATA (Movie) values ('Big Shots');
insert into MOCK_DATA (Movie) values ('Promise Her Anything');
insert into MOCK_DATA (Movie) values ('$ellebrity (Sellebrity)');
insert into MOCK_DATA (Movie) values ('Soul Man');
insert into MOCK_DATA (Movie) values ('Sundowners, The');
insert into MOCK_DATA (Movie) values ('Legends of Oz: Dorothy''s Return');
insert into MOCK_DATA (Movie) values ('Crime Lords of Tokyo');
insert into MOCK_DATA (Movie) values ('One Good Cop');
insert into MOCK_DATA (Movie) values ('Unlikely Weapon, An');
insert into MOCK_DATA (Movie) values ('Taking Sides');
insert into MOCK_DATA (Movie) values ('K-19: The Widowmaker');
insert into MOCK_DATA (Movie) values ('Reversal of Fortune');
insert into MOCK_DATA (Movie) values ('Whole Town''s Talking, The (Passport to Fame)');
insert into MOCK_DATA (Movie) values ('Before and After');
insert into MOCK_DATA (Movie) values ('Human Tornado, The');
insert into MOCK_DATA (Movie) values ('Ulzana''s Raid');
insert into MOCK_DATA (Movie) values ('Alice''s Adventures in Wonderland');
insert into MOCK_DATA (Movie) values ('The Stanford Prison Experiment');
insert into MOCK_DATA (Movie) values ('Harlem Nights');
insert into MOCK_DATA (Movie) values ('Cats & Dogs: The Revenge of Kitty Galore');
insert into MOCK_DATA (Movie) values ('Saawariya');
insert into MOCK_DATA (Movie) values ('Beyond the Door II (Schock) (Shock) (Suspense)');
insert into MOCK_DATA (Movie) values ('There''s Something Wrong with Aunt Diane');
insert into MOCK_DATA (Movie) values ('Paper Man');
insert into MOCK_DATA (Movie) values ('Landscape Suicide');
insert into MOCK_DATA (Movie) values ('King of Devil''s Island (Kongen av Bastøy) ');
insert into MOCK_DATA (Movie) values ('Music and Lyrics');
insert into MOCK_DATA (Movie) values ('I Saw What You Did');
insert into MOCK_DATA (Movie) values ('Spirit of ''76, The');
insert into MOCK_DATA (Movie) values ('When Jews Were Funny');
insert into MOCK_DATA (Movie) values ('Rhinoceros');
insert into MOCK_DATA (Movie) values ('Nömadak TX');
insert into MOCK_DATA (Movie) values ('Creeping Flesh, The');
insert into MOCK_DATA (Movie) values ('Jonny Vang');
insert into MOCK_DATA (Movie) values ('The Fifth Season');
insert into MOCK_DATA (Movie) values ('Babymakers, The');
insert into MOCK_DATA (Movie) values ('Better Things');
insert into MOCK_DATA (Movie) values ('Rat Race');
insert into MOCK_DATA (Movie) values ('Haute Cuisine');
insert into MOCK_DATA (Movie) values ('Ron Clark Story, The');
insert into MOCK_DATA (Movie) values ('The Diary of an Unknown Soldier');
insert into MOCK_DATA (Movie) values ('Terminal Velocity');
insert into MOCK_DATA (Movie) values ('Spirit of the Beehive, The (Espíritu de la colmena, El)');
insert into MOCK_DATA (Movie) values ('Riot on Sunset Strip');
insert into MOCK_DATA (Movie) values ('Creature');
insert into MOCK_DATA (Movie) values ('When Ladies Meet');
insert into MOCK_DATA (Movie) values ('War Is Over, The (Guerre est finie, La)');
insert into MOCK_DATA (Movie) values ('Raanjhanaa');
insert into MOCK_DATA (Movie) values ('Shock Treatment');
insert into MOCK_DATA (Movie) values ('Octagon, The');
insert into MOCK_DATA (Movie) values ('Man of Steel');
insert into MOCK_DATA (Movie) values ('Goat, The (a.k.a. Knock On Wood) (Chèvre, La)');
insert into MOCK_DATA (Movie) values ('U.S. Marshals');
insert into MOCK_DATA (Movie) values ('Love That Boy');
insert into MOCK_DATA (Movie) values ('Eiger Sanction, The');
insert into MOCK_DATA (Movie) values ('Children of Noisy Village, The (a.k.a Children of Bullerby Village, The) (Alla vi barn i Bullerbyn)');
insert into MOCK_DATA (Movie) values ('Advertising and the End of the World');
insert into MOCK_DATA (Movie) values ('Kung Fu Panda Holiday Special');
insert into MOCK_DATA (Movie) values ('Facing the Giants');
insert into MOCK_DATA (Movie) values ('Collapse');
insert into MOCK_DATA (Movie) values ('Just Sex and Nothing Else (Csak szex és más semmi)');
insert into MOCK_DATA (Movie) values ('Who Framed Roger Rabbit?');
insert into MOCK_DATA (Movie) values ('Witness for the Prosecution');
insert into MOCK_DATA (Movie) values ('Paternity');
insert into MOCK_DATA (Movie) values ('American Son');
insert into MOCK_DATA (Movie) values ('Divo, Il');
insert into MOCK_DATA (Movie) values ('Shenandoah');
insert into MOCK_DATA (Movie) values ('Tomorrow Night');
insert into MOCK_DATA (Movie) values ('Do You Like Hitchcock? (Ti piace Hitchcock?)');
insert into MOCK_DATA (Movie) values ('Rainbow Valley');
insert into MOCK_DATA (Movie) values ('Regret to Inform');
insert into MOCK_DATA (Movie) values ('Boy Meets Boy');
insert into MOCK_DATA (Movie) values ('Ichi the Killer (Koroshiya 1)');
insert into MOCK_DATA (Movie) values ('Black Girl (La noire de...)');
insert into MOCK_DATA (Movie) values ('Trip, The');
insert into MOCK_DATA (Movie) values ('Emergo (Apartment 143)');
insert into MOCK_DATA (Movie) values ('Dumb & Dumber (Dumb and Dumber)');
insert into MOCK_DATA (Movie) values ('Mad Dog and Glory');
insert into MOCK_DATA (Movie) values ('Blind Fury');
insert into MOCK_DATA (Movie) values ('Naked Souls');
insert into MOCK_DATA (Movie) values ('Salvatore Giuliano');
insert into MOCK_DATA (Movie) values ('Moving Out');
insert into MOCK_DATA (Movie) values ('Herr Lehmann');
insert into MOCK_DATA (Movie) values ('Faces of Death 5');
insert into MOCK_DATA (Movie) values ('Horse in the Gray Flannel Suit, The');
insert into MOCK_DATA (Movie) values ('Monsignor');
insert into MOCK_DATA (Movie) values ('Collector, The');
insert into MOCK_DATA (Movie) values ('Island at War');
insert into MOCK_DATA (Movie) values ('Unreasonable Man, An');
insert into MOCK_DATA (Movie) values ('Prince of Pennsylvania, The');
insert into MOCK_DATA (Movie) values ('English Patient, The');
insert into MOCK_DATA (Movie) values ('Wild Target');
insert into MOCK_DATA (Movie) values ('Crazy Thunder Road');
insert into MOCK_DATA (Movie) values ('Game 6');
insert into MOCK_DATA (Movie) values ('Battle in Outer Space');
insert into MOCK_DATA (Movie) values ('Glass Bottom Boat, The');
insert into MOCK_DATA (Movie) values ('Go, Go Second Time Virgin (Yuke yuke nidome no shojo)');
insert into MOCK_DATA (Movie) values ('You''re Telling Me!');
insert into MOCK_DATA (Movie) values ('Men at Work');
insert into MOCK_DATA (Movie) values ('Gothic');
insert into MOCK_DATA (Movie) values ('Sweetwater');
insert into MOCK_DATA (Movie) values ('Mon Paradis - Der Winterpalast');
insert into MOCK_DATA (Movie) values ('Red Obession');
insert into MOCK_DATA (Movie) values ('Game Plan, The');
insert into MOCK_DATA (Movie) values ('Hamlet (Gamlet)');
insert into MOCK_DATA (Movie) values ('Supercop 2 (Project S) (Chao ji ji hua)');
insert into MOCK_DATA (Movie) values ('Frankenstein Syndrome, The');
insert into MOCK_DATA (Movie) values ('Three Men and a Cradle (3 hommes et un couffin)');
insert into MOCK_DATA (Movie) values ('Love and Honor');
insert into MOCK_DATA (Movie) values ('Atlas Shrugged: Part II');
insert into MOCK_DATA (Movie) values ('The Thirteen Assassins');
insert into MOCK_DATA (Movie) values ('Muppets, The');
insert into MOCK_DATA (Movie) values ('Cucaracha, La');
insert into MOCK_DATA (Movie) values ('Woman That Dreamed About a Man, The (Kvinden der drømte om en mand)');
insert into MOCK_DATA (Movie) values ('The Boy');
insert into MOCK_DATA (Movie) values ('Soap Girl');
insert into MOCK_DATA (Movie) values ('Devil''s Rain, The');
insert into MOCK_DATA (Movie) values ('Live Nude Girls Unite!');
insert into MOCK_DATA (Movie) values ('Gate II: Trespassers, The');
insert into MOCK_DATA (Movie) values ('From Dusk Till Dawn 2: Texas Blood Money ');
insert into MOCK_DATA (Movie) values ('Cry of the Banshee');
insert into MOCK_DATA (Movie) values ('Dungeons & Dragons');
insert into MOCK_DATA (Movie) values ('Belly of the Beast');
insert into MOCK_DATA (Movie) values ('American Tail, An');
insert into MOCK_DATA (Movie) values ('Cows (Vacas)');
insert into MOCK_DATA (Movie) values ('Force of One, A');
insert into MOCK_DATA (Movie) values ('Paperboy, The');
insert into MOCK_DATA (Movie) values ('You Killed Me First');
insert into MOCK_DATA (Movie) values ('Ingeborg Holm');
insert into MOCK_DATA (Movie) values ('Texas');
insert into MOCK_DATA (Movie) values ('Rocker, The');
insert into MOCK_DATA (Movie) values ('Devil Is a Woman, The');
insert into MOCK_DATA (Movie) values ('Fantasma');
insert into MOCK_DATA (Movie) values ('Chronicle of Anna Magdalena Bach, The (Chronik der Anna Magdalena Bach)');
insert into MOCK_DATA (Movie) values ('Sexo, Amor e Traição');
insert into MOCK_DATA (Movie) values ('If Looks Could Kill');
insert into MOCK_DATA (Movie) values ('Our Dancing Daughters');
insert into MOCK_DATA (Movie) values ('Desert Hearts');
insert into MOCK_DATA (Movie) values ('Command Decision');
insert into MOCK_DATA (Movie) values ('Humble Pie (American Fork)');
insert into MOCK_DATA (Movie) values ('Tale from the Past, A (Përralle Nga e Kaluara)');
insert into MOCK_DATA (Movie) values ('Dead Man''s Shoes');
