insert into Movie (Movie) values ('Extremely Goofy Movie, An');
insert into Movie (Movie) values ('Or (a.k.a. My Treasure)');
insert into Movie (Movie) values ('Wild One, The');
insert into Movie (Movie) values ('Just the Ticket');
insert into Movie (Movie) values ('When the Levees Broke: A Requiem in Four Acts');
insert into Movie (Movie) values ('Mann tut was Mann kann');
insert into Movie (Movie) values ('Bloodfist');
insert into Movie (Movie) values ('Undertow');
insert into Movie (Movie) values ('Narc');
insert into Movie (Movie) values ('Shrooms');
insert into Movie (Movie) values ('Best Laid Plans');
insert into Movie (Movie) values ('Out to Sea');
insert into Movie (Movie) values ('Sorry, Haters');
insert into Movie (Movie) values ('Our Curse');
insert into Movie (Movie) values ('Gate of Heavenly Peace, The');
insert into Movie (Movie) values ('The Winslow Boy');
insert into Movie (Movie) values ('The Divine Woman');
insert into Movie (Movie) values ('Funeral, The');
insert into Movie (Movie) values ('71 Fragments of a Chronology of Chance (71 Fragmente einer Chronologie des Zufalls)');
insert into Movie (Movie) values ('Lucia');
insert into Movie (Movie) values ('Locusts, The');
insert into Movie (Movie) values ('Muppet Christmas Carol, The');
insert into Movie (Movie) values ('Santitos');
insert into Movie (Movie) values ('Stranger by the Lake (L''inconnu du lac)');
insert into Movie (Movie) values ('Princess Yang Kwei Fei (Yôkihi)');
insert into Movie (Movie) values ('The Party');
insert into Movie (Movie) values ('Torpedo Bombers (Torpedonostsy)');
insert into Movie (Movie) values ('City, The (Ciudad, La)');
insert into Movie (Movie) values ('Revenge of the Zombies');
insert into Movie (Movie) values ('Sun Don''t Shine');
insert into Movie (Movie) values ('Captains Courageous');
insert into Movie (Movie) values ('Grabbers');
insert into Movie (Movie) values ('Dinner Guest, The (L''invité)');
insert into Movie (Movie) values ('Cadillac Records');
insert into Movie (Movie) values ('Cinderella Liberty');
insert into Movie (Movie) values ('Crazies, The');
insert into Movie (Movie) values ('Crooklyn');
insert into Movie (Movie) values ('Brothers (Veljekset)');
insert into Movie (Movie) values ('Knucklehead');
insert into Movie (Movie) values ('Rosencrantz and Guildenstern Are Dead');
insert into Movie (Movie) values ('And the Pursuit of Happiness (La poursuite du bonheur)');
insert into Movie (Movie) values ('Mister Roberts');
insert into Movie (Movie) values ('Quiet American, The');
insert into Movie (Movie) values ('Misérables, Les');
insert into Movie (Movie) values ('Horse Soldiers, The');
insert into Movie (Movie) values ('All Fall Down');
insert into Movie (Movie) values ('Eros Plus Massacre (Erosu purasu Gyakusatsu)');
insert into Movie (Movie) values ('I Declare War');
insert into Movie (Movie) values ('Flicker');
insert into Movie (Movie) values ('On the Waterfront');
insert into Movie (Movie) values ('Salt');
insert into Movie (Movie) values ('Whole Wide World, The');
insert into Movie (Movie) values ('Arachnophobia');
insert into Movie (Movie) values ('American Son');
insert into Movie (Movie) values ('Wyoming Renegades');
insert into Movie (Movie) values ('Mr. Denning Drives North');
insert into Movie (Movie) values ('Next');
insert into Movie (Movie) values ('Drunken Tai Chi (Siu taai gik)');
insert into Movie (Movie) values ('Leo the Last');
insert into Movie (Movie) values ('My Letter to George (Mesmerized)');
insert into Movie (Movie) values ('Jean-Luc Cinema Godard');
insert into Movie (Movie) values ('Wonderful Days (a.k.a. Sky Blue)');
insert into Movie (Movie) values ('Just Add Water');
insert into Movie (Movie) values ('Dead Time: Kala');
insert into Movie (Movie) values ('For Neda');
insert into Movie (Movie) values ('Paddington');
insert into Movie (Movie) values ('Venice/Venice');
insert into Movie (Movie) values ('Jesse James');
insert into Movie (Movie) values ('Frozen Land (Paha maa)');
insert into Movie (Movie) values ('The Suspicious Death of a Minor');
insert into Movie (Movie) values ('Kiss Me Again');
insert into Movie (Movie) values ('Young Unknowns, The');
insert into Movie (Movie) values ('Rancho Notorious');
insert into Movie (Movie) values ('Birders: The Central Park Effect (Central Park Effect, The)');
insert into Movie (Movie) values ('Maze, The');
insert into Movie (Movie) values ('Silent Trigger');
insert into Movie (Movie) values ('Powder Room');
insert into Movie (Movie) values ('Ditirambo');
insert into Movie (Movie) values ('Method, The (Método, El)');
insert into Movie (Movie) values ('Dukes, The');
insert into Movie (Movie) values ('Actress, The');
insert into Movie (Movie) values ('Fools'' Parade');
insert into Movie (Movie) values ('Summer Heights High');
insert into Movie (Movie) values ('Ciao Manhattan (Ciao! Manhattan)');
insert into Movie (Movie) values ('Screamers: The Hunting');
insert into Movie (Movie) values ('Saragossa Manuscript, The (Rekopis znaleziony w Saragossie)');
insert into Movie (Movie) values ('Puppet Master 5: The Final Chapter');
insert into Movie (Movie) values ('Shark Alarm at Müggelsee (Hai Alarm am Müggelsee)');
insert into Movie (Movie) values ('Return, The');
insert into Movie (Movie) values ('Collision: Christopher Hitchens vs. Douglas Wilson');
insert into Movie (Movie) values ('Year of the Jellyfish (L''année des méduses)');
insert into Movie (Movie) values ('Separation, The (Séparation, La)');
insert into Movie (Movie) values ('Smile');
insert into Movie (Movie) values ('Five-Year Engagement, The');
insert into Movie (Movie) values ('Casablanca Express');
insert into Movie (Movie) values ('Passeio com Johnny Guitar');
insert into Movie (Movie) values ('Anthony Adverse');
insert into Movie (Movie) values ('Ice Castles');
insert into Movie (Movie) values ('Adanggaman');
insert into Movie (Movie) values ('Shamrock Handicap, The');
insert into Movie (Movie) values ('Halloween 4: The Return of Michael Myers');
insert into Movie (Movie) values ('My Mom Is a Character (Minha Mãe é uma Peça: O Filme)');
insert into Movie (Movie) values ('Hip Hop Witch, Da');
insert into Movie (Movie) values ('Guinevere');
insert into Movie (Movie) values ('Dead Set');
insert into Movie (Movie) values ('Goke, Body Snatcher from Hell (Kyuketsuki Gokemidoro)');
insert into Movie (Movie) values ('Very Harold & Kumar 3D Christmas, A');
insert into Movie (Movie) values ('Complete History of My Sexual Failures, A');
insert into Movie (Movie) values ('Butchered');
insert into Movie (Movie) values ('New Gladiators (I guerrieri dell''anno 2072)');
insert into Movie (Movie) values ('Invisible War, The');
insert into Movie (Movie) values ('Bird');
insert into Movie (Movie) values ('Venom');
insert into Movie (Movie) values ('Ox-Bow Incident, The');
insert into Movie (Movie) values ('Children of the Damned');
insert into Movie (Movie) values ('Daddy Long Legs');
insert into Movie (Movie) values ('Three Little Words');
insert into Movie (Movie) values ('Hitman Hart: Wrestling with Shadows');
insert into Movie (Movie) values ('Things I Like, Things I Don''t Like (Foutaises)');
insert into Movie (Movie) values ('Under Siege 2: Dark Territory');
insert into Movie (Movie) values ('American Dream');
insert into Movie (Movie) values ('White, Red and Verdone');
insert into Movie (Movie) values ('White Countess, The');
insert into Movie (Movie) values ('Dragonslayer');
insert into Movie (Movie) values ('Brutal Relax');
insert into Movie (Movie) values ('Fool for Love');
insert into Movie (Movie) values ('Avengers, The');
insert into Movie (Movie) values ('Guns of the Magnificent Seven');
insert into Movie (Movie) values ('Interior. Leather Bar.');
insert into Movie (Movie) values ('Factory Girl');
insert into Movie (Movie) values ('The Garden of Sinners - Chapter 5: Paradox Paradigm');
insert into Movie (Movie) values ('Mo'' Money');
insert into Movie (Movie) values ('It''s a Gift');
insert into Movie (Movie) values ('Prime of Miss Jean Brodie, The');
insert into Movie (Movie) values ('At the Earth''s Core');
insert into Movie (Movie) values ('Five Graves to Cairo');
insert into Movie (Movie) values ('Buffet froid');
insert into Movie (Movie) values ('Hitman, The');
insert into Movie (Movie) values ('Two Weeks Notice');
insert into Movie (Movie) values ('Decalogue, The (Dekalog)');
insert into Movie (Movie) values ('Empire');
insert into Movie (Movie) values ('Frisco Kid, The');
insert into Movie (Movie) values ('Find Love');
insert into Movie (Movie) values ('True Colors');
insert into Movie (Movie) values ('Meeting Evil');
insert into Movie (Movie) values ('Bronx Tale, A');
insert into Movie (Movie) values ('The Shadow of the Eagle');
insert into Movie (Movie) values ('Mars');
insert into Movie (Movie) values ('Artois the Goat');
insert into Movie (Movie) values ('One Night with the King');
insert into Movie (Movie) values ('The Power and the Glory');
insert into Movie (Movie) values ('Grimm Love (Rohtenburg)');
insert into Movie (Movie) values ('St. George Shoots the Dragon (Sveti Georgije ubiva azdahu)');
insert into Movie (Movie) values ('Lathe of Heaven');
insert into Movie (Movie) values ('Dream Wife');
insert into Movie (Movie) values ('Forbidden Fruit (Kielletty hedelmä)');
insert into Movie (Movie) values ('Smilla''s Sense of Snow');
insert into Movie (Movie) values ('Halloween H20: 20 Years Later (Halloween 7: The Revenge of Laurie Strode)');
insert into Movie (Movie) values ('Eila');
insert into Movie (Movie) values ('28 Up');
insert into Movie (Movie) values ('Death Note');
insert into Movie (Movie) values ('Voices');
insert into Movie (Movie) values ('Don''t Be a Menace to South Central While Drinking Your Juice in the Hood');
insert into Movie (Movie) values ('Bullet for a Badman (Renegade Posse)');
insert into Movie (Movie) values ('Honey Pot, The');
insert into Movie (Movie) values ('Susana (Devil and the Flesh, The)');
insert into Movie (Movie) values ('Downeast');
insert into Movie (Movie) values ('Make Mine Music');
insert into Movie (Movie) values ('Ken Park');
insert into Movie (Movie) values ('Amish Murder, An');
insert into Movie (Movie) values ('Diverted');
insert into Movie (Movie) values ('Star Packer, The');
insert into Movie (Movie) values ('King Kong Escapes (Kingu Kongu no gyakushû)');
insert into Movie (Movie) values ('I Accuse');
insert into Movie (Movie) values ('Fanboys');
insert into Movie (Movie) values ('Charlie Chan''s Chance');
insert into Movie (Movie) values ('Sunday Bloody Sunday');
insert into Movie (Movie) values ('Omega Doom');
insert into Movie (Movie) values ('Out of Bounds');
insert into Movie (Movie) values ('King of the Zombies');
insert into Movie (Movie) values ('Haunted Castle, The (Schloß Vogeloed)');
insert into Movie (Movie) values ('Ménage (Tenue de soirée)');
insert into Movie (Movie) values ('12 Rounds');
insert into Movie (Movie) values ('Imposter, The');
insert into Movie (Movie) values ('Larks on a String (Skrivánci na niti)');
insert into Movie (Movie) values ('The Fifth Season');
insert into Movie (Movie) values ('The Sinners of Hell');
insert into Movie (Movie) values ('B.T.K.');
insert into Movie (Movie) values ('Paper Will Be Blue, The (Hîrtia va fi albastrã)');
insert into Movie (Movie) values ('Green Lantern: Emerald Knights');
insert into Movie (Movie) values ('Feuer, Eis & Dosenbier');
insert into Movie (Movie) values ('Trash');
insert into Movie (Movie) values ('Keeper of Lost Causes, The (Kvinden i buret)');
insert into Movie (Movie) values ('El Hada Buena - Una Fábula Peronista');
insert into Movie (Movie) values ('Cran d''arrêt');
insert into Movie (Movie) values ('Tangled Ever After');
insert into Movie (Movie) values ('What Time Is It There? (Ni neibian jidian)');
insert into Movie (Movie) values ('Last Song, The');
insert into Movie (Movie) values ('Yolki 2');
insert into Movie (Movie) values ('Lady in Cement');
insert into Movie (Movie) values ('Changing Lanes');
insert into Movie (Movie) values ('Charlie Chan in Shanghai');
insert into Movie (Movie) values ('Doghouse');
insert into Movie (Movie) values ('Taming of the Shrew, The');
insert into Movie (Movie) values ('Place in the Sun, A');
insert into Movie (Movie) values ('Outcast of the Islands');
insert into Movie (Movie) values ('Halloween');
insert into Movie (Movie) values ('Filly Brown');
insert into Movie (Movie) values ('Spite Marriage');
insert into Movie (Movie) values ('Misérables, Les');
insert into Movie (Movie) values ('Man from Earth, The');
insert into Movie (Movie) values ('Ladrón que roba a ladrón');
insert into Movie (Movie) values ('Starting Over');
insert into Movie (Movie) values ('Notorious C.H.O.');
insert into Movie (Movie) values ('Cross: The Arthur Blessitt Story, The');
insert into Movie (Movie) values ('Moscow Does Not Believe in Tears (Moskva slezam ne verit)');
insert into Movie (Movie) values ('Dragon Hunters (Chasseurs de dragons)');
insert into Movie (Movie) values ('Green Hornet, The');
insert into Movie (Movie) values ('Hard Word, The');
insert into Movie (Movie) values ('Arrested Development Documentary Project, The');
insert into Movie (Movie) values ('Testament');
insert into Movie (Movie) values ('Palm Beach Story, The');
insert into Movie (Movie) values ('Rock the Boat');
insert into Movie (Movie) values ('Escobar: Paradise Lost');
insert into Movie (Movie) values ('Shaft');
insert into Movie (Movie) values ('10th Judicial Court: Judicial Hearings, The (10e chambre - Instants d''audience)');
insert into Movie (Movie) values ('Eversmile, New Jersey');
insert into Movie (Movie) values ('Entertainer, The');
insert into Movie (Movie) values ('Killers from Space');
insert into Movie (Movie) values ('Dunce Class on Vacation, The (Hababam sinifi tatilde)');
insert into Movie (Movie) values ('Calamari Union');
insert into Movie (Movie) values ('HellBent');
insert into Movie (Movie) values ('Great Train Robbery, The (a.k.a. First Great Train Robbery, The)');
insert into Movie (Movie) values ('No Strings Attached');
insert into Movie (Movie) values ('Family Friend, The (L''amico di famiglia)');
insert into Movie (Movie) values ('John Huston: The Man, the Movies, the Maverick');
insert into Movie (Movie) values ('I See a Dark Stranger');
insert into Movie (Movie) values ('An Empress and the Warriors');
insert into Movie (Movie) values ('Someone to Watch Over Me');
insert into Movie (Movie) values ('Tu£sday');
insert into Movie (Movie) values ('Overnighters, The');
insert into Movie (Movie) values ('Fatty Drives the Bus');
insert into Movie (Movie) values ('Après lui');
insert into Movie (Movie) values ('Secret Life of Bees, The');
insert into Movie (Movie) values ('Vääpeli Körmy ja kahtesti laukeava');
insert into Movie (Movie) values ('Uncommon Valor');
insert into Movie (Movie) values ('Nils Karlsson Pyssling');
insert into Movie (Movie) values ('Tell It to the Marines');
insert into Movie (Movie) values ('High and Dry');
insert into Movie (Movie) values ('Watch the Birdie');
insert into Movie (Movie) values ('No and Me (No et moi)');
insert into Movie (Movie) values ('Karate Kid, The');
insert into Movie (Movie) values ('Shifty');
insert into Movie (Movie) values ('Frozen');
insert into Movie (Movie) values ('White Reindeer, The (Valkoinen peura)');
insert into Movie (Movie) values ('American Vagabond');
insert into Movie (Movie) values ('I Saw What You Did');
insert into Movie (Movie) values ('Star Trek');
insert into Movie (Movie) values ('Conformist, The (Conformista, Il)');
insert into Movie (Movie) values ('Trapeze');
insert into Movie (Movie) values ('Not Reconciled (Nicht versöhnt oder Es hilft nur Gewalt wo Gewalt herrscht)');
insert into Movie (Movie) values ('Swept Away (Travolti da un insolito destino nell''azzurro mare d''Agosto)');
insert into Movie (Movie) values ('Devil''s Rejects, The');
insert into Movie (Movie) values ('Desperately Seeking Susan');
insert into Movie (Movie) values ('Happy Birthday to Me');
insert into Movie (Movie) values ('Muddy River');
insert into Movie (Movie) values ('Special Delivery');
insert into Movie (Movie) values ('Undefeatable');
insert into Movie (Movie) values ('Cruel Romance, A (Zhestokij Romans)');
insert into Movie (Movie) values ('St. Vincent');
insert into Movie (Movie) values ('Salaam Cinema');
insert into Movie (Movie) values ('Once Upon a Crime...');
insert into Movie (Movie) values ('To Sleep with Anger');
insert into Movie (Movie) values ('Hitchcock');
insert into Movie (Movie) values ('Honey, We Shrunk Ourselves');
insert into Movie (Movie) values ('Zathura');
insert into Movie (Movie) values ('My Mom Is a Character (Minha Mãe é uma Peça: O Filme)');
insert into Movie (Movie) values ('Waltzes from Vienna');
insert into Movie (Movie) values ('Wheelmen');
insert into Movie (Movie) values ('Don Juan');
insert into Movie (Movie) values ('Madagascar');
insert into Movie (Movie) values ('Snow White (Blancanieves)');
insert into Movie (Movie) values ('Thomas Crown Affair, The');
insert into Movie (Movie) values ('Peggy Sue Got Married');
insert into Movie (Movie) values ('Midway');
insert into Movie (Movie) values ('Texas Chainsaw 3D');
insert into Movie (Movie) values ('Homeward Bound II: Lost in San Francisco');
insert into Movie (Movie) values ('Broken Wings (Knafayim Shvurot)');
insert into Movie (Movie) values ('Alatriste');
insert into Movie (Movie) values ('Fugly!');
insert into Movie (Movie) values ('Godzilla 1985: The Legend Is Reborn (Gojira) (Godzilla) (Return of Godzilla, The)');
insert into Movie (Movie) values ('Yes');
insert into Movie (Movie) values ('Shop Around the Corner, The');
insert into Movie (Movie) values ('Gun Shy');
insert into Movie (Movie) values ('Telling You');
insert into Movie (Movie) values ('Baxter, The');
insert into Movie (Movie) values ('Larceny, Inc.');
insert into Movie (Movie) values ('New One-Armed Swordsman, The (Xin du bi dao)');
insert into Movie (Movie) values ('Taking of Pelham One Two Three, The');
insert into Movie (Movie) values ('Tom and Jerry: A Nutcracker Tale');
insert into Movie (Movie) values ('Last Stand At Saber River');
insert into Movie (Movie) values ('1990: The Bronx Warriors (1990: I guerrieri del Bronx)');
insert into Movie (Movie) values ('Dance, Girl, Dance');
insert into Movie (Movie) values ('Getting Back to Abnormal');
insert into Movie (Movie) values ('Pope of Greenwich Village, The');
insert into Movie (Movie) values ('Dangerous Beauty');
insert into Movie (Movie) values ('Wrestling Queens');
insert into Movie (Movie) values ('Buy the Ticket, Take the Ride: Hunter S. Thompson on Film');
insert into Movie (Movie) values ('Dangerous Corner');
insert into Movie (Movie) values ('Drop, The');
insert into Movie (Movie) values ('Operación Cannabis');
insert into Movie (Movie) values ('Brewster''s Millions');
insert into Movie (Movie) values ('Sex and Breakfast');
insert into Movie (Movie) values ('Best of the Best');
insert into Movie (Movie) values ('Waking Up in Reno');
insert into Movie (Movie) values ('Boy (Shônen)');
insert into Movie (Movie) values ('Kevin & Perry Go Large');
insert into Movie (Movie) values ('Sittin'' on a Backyard Fence');
insert into Movie (Movie) values ('Mean Machine');
insert into Movie (Movie) values ('Two Much');
insert into Movie (Movie) values ('Scandal');
insert into Movie (Movie) values ('Dr. Who and the Daleks');
insert into Movie (Movie) values ('Miracle');
insert into Movie (Movie) values ('Aaltra');
insert into Movie (Movie) values ('Slaughter');
insert into Movie (Movie) values ('Woman That Dreamed About a Man, The (Kvinden der drømte om en mand)');
insert into Movie (Movie) values ('3 Ring Circus');
insert into Movie (Movie) values ('Pope Joan (Die Päpstin)');
insert into Movie (Movie) values ('Bertsolari');
insert into Movie (Movie) values ('Painted Veil, The');
insert into Movie (Movie) values ('Jade');
insert into Movie (Movie) values ('Geek Charming');
insert into Movie (Movie) values ('Intimate Relations');
insert into Movie (Movie) values ('Paradise: Faith (Paradies: Glaube)');
insert into Movie (Movie) values ('Our Modern Maidens');
insert into Movie (Movie) values ('The Gamma People');
insert into Movie (Movie) values ('Remember Me (Ricordati di me)');
insert into Movie (Movie) values ('Täynnä Tarmoa');
insert into Movie (Movie) values ('Selfish Giant, The');
insert into Movie (Movie) values ('Brothers Rico, The');
insert into Movie (Movie) values ('Freud: The Secret Passion');
insert into Movie (Movie) values ('Outrage');
insert into Movie (Movie) values ('8 (8, the Play)');
insert into Movie (Movie) values ('Clouds of May (Mayis sikintisi)');
insert into Movie (Movie) values ('Little Engine That Could, The');
insert into Movie (Movie) values ('Boys in the Band, The');
insert into Movie (Movie) values ('Cazuza - O Tempo Não Pára');
insert into Movie (Movie) values ('Last Ride');
insert into Movie (Movie) values ('Raw Meat (Death Line)');
insert into Movie (Movie) values ('From One Second to the Next');
insert into Movie (Movie) values ('Boom Town');
insert into Movie (Movie) values ('Sicily! (Sicilia!)');
insert into Movie (Movie) values ('Nukes in Space');
insert into Movie (Movie) values ('Spencer''s Mountain');
insert into Movie (Movie) values ('Madagascar 3: Europe''s Most Wanted');
insert into Movie (Movie) values ('Won Ton Ton: The Dog Who Saved Hollywood');
insert into Movie (Movie) values ('God''s Not Dead');
insert into Movie (Movie) values ('Immortel (ad vitam) (Immortal)');
insert into Movie (Movie) values ('Cadence');
insert into Movie (Movie) values ('Buona Sera, Mrs. Campbell');
insert into Movie (Movie) values ('Kiki');
insert into Movie (Movie) values ('After the Rehearsal (Efter repetitionen)');
insert into Movie (Movie) values ('Surplus: Terrorized Into Being Consumers');
insert into Movie (Movie) values ('No Turning Back');
insert into Movie (Movie) values ('Beast with Five Fingers, The');
insert into Movie (Movie) values ('Singapore Sling (Singapore sling: O anthropos pou agapise ena ptoma)');
insert into Movie (Movie) values ('District 13 (Banlieue 13)');
insert into Movie (Movie) values ('Born into Brothels');
insert into Movie (Movie) values ('10th Judicial Court: Judicial Hearings, The (10e chambre - Instants d''audience)');
insert into Movie (Movie) values ('Hairspray');
insert into Movie (Movie) values ('We Live in Public');
insert into Movie (Movie) values ('Bird');
insert into Movie (Movie) values ('Restless (Uro)');
insert into Movie (Movie) values ('Get Over It');
insert into Movie (Movie) values ('Bitter Sweet');
insert into Movie (Movie) values ('Go Figure (Va savoir)');
insert into Movie (Movie) values ('Cold Comfort Farm');
insert into Movie (Movie) values ('Dirty');
insert into Movie (Movie) values ('Lone Wolf and Cub: Baby Cart at the River Styx (Kozure Ôkami: Sanzu no kawa no ubaguruma)');
insert into Movie (Movie) values ('Matter of Dignity, A (To teleftaio psema)');
insert into Movie (Movie) values ('Dutchman');
insert into Movie (Movie) values ('Crime and Punishment in Suburbia');
insert into Movie (Movie) values ('Satanas');
insert into Movie (Movie) values ('Afro Samurai: Resurrection');
insert into Movie (Movie) values ('Tepenin Ardi');
insert into Movie (Movie) values ('How the Grinch Stole Christmas!');
insert into Movie (Movie) values ('The Hire: Beat the Devil');
insert into Movie (Movie) values ('Ninja Cheerleaders');
insert into Movie (Movie) values ('Flatfoot on the Nile (Piedone d''Egitto)');
insert into Movie (Movie) values ('Love Me or Leave Me');
insert into Movie (Movie) values ('Von Richthofen and Brown');
insert into Movie (Movie) values ('Martin & Orloff');
insert into Movie (Movie) values ('When the Levees Broke: A Requiem in Four Acts');
insert into Movie (Movie) values ('Out On A Limb');
insert into Movie (Movie) values ('Cain and Mabel');
insert into Movie (Movie) values ('Crimson Rivers 2: Angels of the Apocalypse (Rivières pourpres II - Les anges de l''apocalypse, Les)');
insert into Movie (Movie) values ('Louise Bourgeois: The Spider, the Mistress and the Tangerine');
insert into Movie (Movie) values ('Scorpion King 2: Rise of a Warrior, The');
insert into Movie (Movie) values ('I Bury the Living');
insert into Movie (Movie) values ('Medora');
insert into Movie (Movie) values ('8 ½ Women (a.k.a. 8 1/2 Women) (a.k.a. Eight and a Half Women)');
insert into Movie (Movie) values ('Potiche');
insert into Movie (Movie) values ('How High');
insert into Movie (Movie) values ('Boys (Drenge)');
insert into Movie (Movie) values ('A Gathering of Eagles');
insert into Movie (Movie) values ('Super Fuzz (a.k.a. Super Snooper) (Poliziotto superpiù)');
insert into Movie (Movie) values ('Wes Craven''s New Nightmare (Nightmare on Elm Street Part 7: Freddy''s Finale, A)');
insert into Movie (Movie) values ('Loose Change 9/11: An American Coup');
insert into Movie (Movie) values ('Firefox');
insert into Movie (Movie) values ('Hypothesis of the Stolen Painting, The (L''hypothèse du tableau volé)');
insert into Movie (Movie) values ('City Zero');
insert into Movie (Movie) values ('My Wife Is a Gangster (Jopog manura)');
insert into Movie (Movie) values ('Houseguest');
insert into Movie (Movie) values ('Me You Them (Eu, Tu, Eles)');
insert into Movie (Movie) values ('Monsieur Hire');
insert into Movie (Movie) values ('American Reunion (American Pie 4)');
insert into Movie (Movie) values ('Paris, Texas');
insert into Movie (Movie) values ('In the Soup');
insert into Movie (Movie) values ('Gate of Flesh (Nikutai no mon)');
insert into Movie (Movie) values ('Down and Out with the Dolls');
insert into Movie (Movie) values ('National Lampoon''s Lady Killers (National Lampoon''s Gold Diggers)');
insert into Movie (Movie) values ('Whisper of Sin (Nuodemes uzkalbejimas)');
insert into Movie (Movie) values ('Parent Trap, The');
insert into Movie (Movie) values ('Château, The');
insert into Movie (Movie) values ('It Could Happen to You');
insert into Movie (Movie) values ('Palms (Ladoni)');
insert into Movie (Movie) values ('Annie Get Your Gun');
insert into Movie (Movie) values ('Happy');
insert into Movie (Movie) values ('Blue Like Jazz');
insert into Movie (Movie) values ('Calloused Hands');
insert into Movie (Movie) values ('Broken Kingdom');
insert into Movie (Movie) values ('Absolute Power');
insert into Movie (Movie) values ('Strayed (égarés, Les)');
insert into Movie (Movie) values ('Hatari!');
insert into Movie (Movie) values ('Salvador (Puig Antich)');
insert into Movie (Movie) values ('Felicia''s Journey');
insert into Movie (Movie) values ('Me and You and Everyone We Know');
insert into Movie (Movie) values ('Bone');
insert into Movie (Movie) values ('Barbie in the Nutcracker');
insert into Movie (Movie) values ('Trials of Darryl Hunt, The');
insert into Movie (Movie) values ('Red Dwarf, The (Nain rouge, Le)');
insert into Movie (Movie) values ('Delivery Man');
insert into Movie (Movie) values ('Hawaii');
insert into Movie (Movie) values ('Gertrud');
insert into Movie (Movie) values ('Tenacious D in The Pick of Destiny');
insert into Movie (Movie) values ('Latcho Drom');
insert into Movie (Movie) values ('Midnight Run');
insert into Movie (Movie) values ('Woman Always Pays, The (Afgrunden) (Abyss, The)');
insert into Movie (Movie) values ('Great Day in Harlem, A');
insert into Movie (Movie) values ('Tabloid');
insert into Movie (Movie) values ('Most Hated Family in America, The');
insert into Movie (Movie) values ('Parked');
insert into Movie (Movie) values ('Jingle All the Way');
insert into Movie (Movie) values ('Andromeda Strain, The');
insert into Movie (Movie) values ('Little Red Flowers (Kan shang qu hen mei)');
insert into Movie (Movie) values ('American Gigolo');
insert into Movie (Movie) values ('Wrong Move, The (Falsche Bewegung)');
insert into Movie (Movie) values ('Queen and I, The (Drottningen och jag)');
insert into Movie (Movie) values ('Death Watch (La Mort en Direct)');
insert into Movie (Movie) values ('This Man Must Die (Que la bête meure)');
insert into Movie (Movie) values ('Welcome Back, Mr. McDonald (Rajio no jikan)');
insert into Movie (Movie) values ('High on Crack Street: Lost Lives in Lowell');
insert into Movie (Movie) values ('Five Angles on Murder');
insert into Movie (Movie) values ('In Therapy (Divã)');
insert into Movie (Movie) values ('Killer Condom (Kondom des Grauens)');
insert into Movie (Movie) values ('Slaughter');
insert into Movie (Movie) values ('Fade to Black');
insert into Movie (Movie) values ('Terrace, The (Terrazza, La)');
insert into Movie (Movie) values ('I Am Love (Io sono l''amore)');
insert into Movie (Movie) values ('Heaven Is for Real');
insert into Movie (Movie) values ('Live from Baghdad');
insert into Movie (Movie) values ('Kid, The');
insert into Movie (Movie) values ('Boogeyman, The');
insert into Movie (Movie) values ('Forget Me Not');
insert into Movie (Movie) values ('Russia 88');
insert into Movie (Movie) values ('Branded');
insert into Movie (Movie) values ('Star Wars: Episode II - Attack of the Clones');
insert into Movie (Movie) values ('Parasites, Les');
insert into Movie (Movie) values ('So Ends Our Night');
insert into Movie (Movie) values ('Black Death');
insert into Movie (Movie) values ('Rich Man''s Wife, The');
insert into Movie (Movie) values ('Good News');
insert into Movie (Movie) values ('Any Number Can Play');
insert into Movie (Movie) values ('Lord of War');
insert into Movie (Movie) values ('Meantime');
insert into Movie (Movie) values ('Hitch-Hiker, The');
insert into Movie (Movie) values ('Täynnä Tarmoa');
insert into Movie (Movie) values ('Hobbit, The');
insert into Movie (Movie) values ('Last Dragon, The');
insert into Movie (Movie) values ('Visit, The');
insert into Movie (Movie) values ('Burning Secret');
insert into Movie (Movie) values ('Digging to China');
insert into Movie (Movie) values ('Football Factory, The');
insert into Movie (Movie) values ('The Power and the Glory');
insert into Movie (Movie) values ('Garage Olimpo');
insert into Movie (Movie) values ('Paris by Night');
insert into Movie (Movie) values ('Woman in the Meadow (Nainen kedolla)');
insert into Movie (Movie) values ('Mr. Morgan''s Last Love');
insert into Movie (Movie) values ('Who Pulled the Plug? (Göta kanal eller Vem drog ur proppen?)');
insert into Movie (Movie) values ('Big River Man');
insert into Movie (Movie) values ('Act of Killing, The');
insert into Movie (Movie) values ('Kevin Hart: Let Me Explain');
insert into Movie (Movie) values ('Master of Ballantrae, The');
insert into Movie (Movie) values ('Portrait in Black');
insert into Movie (Movie) values ('Scary Movie 3');
insert into Movie (Movie) values ('These Girls');
insert into Movie (Movie) values ('Introducing Dorothy Dandridge');
insert into Movie (Movie) values ('New York Confidential');
insert into Movie (Movie) values ('Madhouse');
insert into Movie (Movie) values ('Mahler');
insert into Movie (Movie) values ('Tarzan the Fearless');
insert into Movie (Movie) values ('Emperor''s New Groove 2: Kronk''s New Groove, The');
insert into Movie (Movie) values ('Zabriskie Point');
insert into Movie (Movie) values ('The Adventures of Hercules');
insert into Movie (Movie) values ('One, The');
insert into Movie (Movie) values ('Manon of the Spring (Manon des sources)');
insert into Movie (Movie) values ('Tentacles (Tentacoli)');
insert into Movie (Movie) values ('Born on the Fourth of July');
insert into Movie (Movie) values ('Henry IV, Part II (Second Part of King Henry the Fourth, including his death and the coronation of King Henry the Fifth, The)');
insert into Movie (Movie) values ('Gigi');
insert into Movie (Movie) values ('Sweet Home');
insert into Movie (Movie) values ('Standing in the Shadows of Motown');
insert into Movie (Movie) values ('Santa Claus');
insert into Movie (Movie) values ('Rage of Honor');
insert into Movie (Movie) values ('Restaurant');
insert into Movie (Movie) values ('Shaft');
insert into Movie (Movie) values ('Legend of the Guardians: The Owls of Ga''Hoole');
insert into Movie (Movie) values ('Sympathy for Mr. Vengeance (Boksuneun naui geot)');
insert into Movie (Movie) values ('Little Drummer Boy, The');
insert into Movie (Movie) values ('Miracles');
insert into Movie (Movie) values ('Darkness');
insert into Movie (Movie) values ('Action in the North Atlantic');
insert into Movie (Movie) values ('Independent, The');
insert into Movie (Movie) values ('Samsara');
insert into Movie (Movie) values ('Zone Troopers');
insert into Movie (Movie) values ('Fall');
insert into Movie (Movie) values ('Patton Oswalt: No Reason to Complain');
insert into Movie (Movie) values ('New York: A Documentary Film');
insert into Movie (Movie) values ('Sovereign''s Company');
insert into Movie (Movie) values ('Footprints on the Moon (Le orme) (Primal Impulse)');
insert into Movie (Movie) values ('Lured');
insert into Movie (Movie) values ('Vexille (Bekushiru: 2077 Nihon sakoku)');
insert into Movie (Movie) values ('Electra, My Love (Szerelmem, Elektra)');
insert into Movie (Movie) values ('Castles in the Sky');
insert into Movie (Movie) values ('[REC] 4: Apocalypse');
insert into Movie (Movie) values ('Kokowääh');
insert into Movie (Movie) values ('Diary of a Country Priest (Journal d''un curé de campagne)');
insert into Movie (Movie) values ('Let''s Make Love');
insert into Movie (Movie) values ('Gabby Douglas Story, The');
insert into Movie (Movie) values ('Replacements, The');
insert into Movie (Movie) values ('Kagi (Odd Obsession)');
insert into Movie (Movie) values ('Family Guy Presents: Blue Harvest');
insert into Movie (Movie) values ('Where the Red Fern Grows');
insert into Movie (Movie) values ('State of Siege (État de siège)');
insert into Movie (Movie) values ('Viy or Spirit of Evil (Viy)');
insert into Movie (Movie) values ('I Confess');
insert into Movie (Movie) values ('Notti bianche, Le (White Nights)');
insert into Movie (Movie) values ('Escape Plan');
insert into Movie (Movie) values ('Special Bulletin');
insert into Movie (Movie) values ('Man with the Golden Arm, The');
insert into Movie (Movie) values ('Red Dust');
insert into Movie (Movie) values ('Beekeeper, The (O melissokomos)');
insert into Movie (Movie) values ('In Enemy Hands');
insert into Movie (Movie) values ('Tenderness');
insert into Movie (Movie) values ('Angels & Demons');
insert into Movie (Movie) values ('Gangs of New York');
insert into Movie (Movie) values ('Zarafa');
insert into Movie (Movie) values ('Mole People, The');
insert into Movie (Movie) values ('Wave, The (Welle, Die)');
insert into Movie (Movie) values ('Michael Jordan to the Max');
insert into Movie (Movie) values ('For a Lost Soldier (Voor een Verloren Soldaat)');
insert into Movie (Movie) values ('Sweet Liberty');
insert into Movie (Movie) values ('Mission Bloody Mary');
insert into Movie (Movie) values ('Wrath of God, The');
insert into Movie (Movie) values ('Touch of Evil');
insert into Movie (Movie) values ('Yu-Gi-Oh!: Bonds Beyond Time (Gekijouban Yuugiou: Chouyuugou! Jikuu o koeta kizuna)');
insert into Movie (Movie) values ('Nine Lives (Ni liv)');
insert into Movie (Movie) values ('Tepenin Ardi');
insert into Movie (Movie) values ('Knack ...and How to Get It, The');
insert into Movie (Movie) values ('Edge of Tomorrow');
insert into Movie (Movie) values ('Stand Up Guys');
insert into Movie (Movie) values ('Lilies');
insert into Movie (Movie) values ('Chase, The');
insert into Movie (Movie) values ('Matrix, The');
insert into Movie (Movie) values ('Devil''s Double, The');
insert into Movie (Movie) values ('Sasha (Sascha)');
insert into Movie (Movie) values ('Children in the Wind (Kaze no naka no kodomo)');
insert into Movie (Movie) values ('History of Future Folk, The');
insert into Movie (Movie) values ('Aberdeen');
insert into Movie (Movie) values ('Kindred, The');
insert into Movie (Movie) values ('Metropolis');
insert into Movie (Movie) values ('This Special Friendship (Les amitiés particulières)');
insert into Movie (Movie) values ('Zatoichi the Fugitive (Zatôichi kyôjô-tabi) (Zatôichi 4)');
insert into Movie (Movie) values ('Rosie');
insert into Movie (Movie) values ('Higher Ground');
insert into Movie (Movie) values ('Nacho Libre');
insert into Movie (Movie) values ('Numbskull Emptybrook (Uuno Turhapuro)');
insert into Movie (Movie) values ('West Point');
insert into Movie (Movie) values ('Dragon Lord (a.k.a. Dragon Strike) (Long Xiao Ye)');
insert into Movie (Movie) values ('Cloudburst');
insert into Movie (Movie) values ('Who Killed Vincent Chin?');
insert into Movie (Movie) values ('Sometimes Happiness, Sometimes Sorrow (Kabhi Khushi Kabhie Gham)');
insert into Movie (Movie) values ('Cousin Bette');
insert into Movie (Movie) values ('Attack of the 50ft Cheerleader');
insert into Movie (Movie) values ('French Connection II');
insert into Movie (Movie) values ('E Aí... Comeu?');
insert into Movie (Movie) values ('Hum Tum');
insert into Movie (Movie) values ('Get Over It');
insert into Movie (Movie) values ('Avalon');
insert into Movie (Movie) values ('Dying Room Only');
insert into Movie (Movie) values ('Saving God');
insert into Movie (Movie) values ('Boys Don''t Cry');
insert into Movie (Movie) values ('Hounddog');
insert into Movie (Movie) values ('All the Light in the Sky');
insert into Movie (Movie) values ('Good Man in Africa, A');
insert into Movie (Movie) values ('Hi Diddle Diddle');
insert into Movie (Movie) values ('Boomerang');
insert into Movie (Movie) values ('Day of the Locust, The');
insert into Movie (Movie) values ('Night Falls on Manhattan');
insert into Movie (Movie) values ('Goodbye First Love');
insert into Movie (Movie) values ('Nancy Drew and the Hidden Staircase');
insert into Movie (Movie) values ('Rapid Fire');
insert into Movie (Movie) values ('The Emperor''s Club');
insert into Movie (Movie) values ('Frequencies');
insert into Movie (Movie) values ('Fährmann Maria');
insert into Movie (Movie) values ('Gone');
insert into Movie (Movie) values ('Cheech & Chong''s The Corsican Brothers');
insert into Movie (Movie) values ('Gregory Go Boom');
insert into Movie (Movie) values ('Xuxa in Crystal Moon');
insert into Movie (Movie) values ('Barenaked in America');
insert into Movie (Movie) values ('Un Piede in paradiso');
insert into Movie (Movie) values ('First Day of the Rest of Your Life, The (Le premier jour du reste de ta vie)');
insert into Movie (Movie) values ('Just Sex and Nothing Else (Csak szex és más semmi)');
insert into Movie (Movie) values ('Cold Turkey');
insert into Movie (Movie) values ('Rudy');
insert into Movie (Movie) values ('Maryam');
insert into Movie (Movie) values ('Cleaner');
insert into Movie (Movie) values ('Too Shy to Try (Je suis timide... mais je me soigne)');
insert into Movie (Movie) values ('Ruby');
insert into Movie (Movie) values ('Earth vs. the Spider');
insert into Movie (Movie) values ('Recruiter, The');
insert into Movie (Movie) values ('Rich Man''s Wife, The');
insert into Movie (Movie) values ('Leaves from Satan''s Book (Blade af Satans bog)');
insert into Movie (Movie) values ('Ghost in the Shell 2: Innocence (a.k.a. Innocence) (Inosensu)');
insert into Movie (Movie) values ('Stepfather, The');
insert into Movie (Movie) values ('Bad Dreams');
insert into Movie (Movie) values ('Bill Burr: Let It Go');
insert into Movie (Movie) values ('Elementary Particles, The (Elementarteilchen)');
insert into Movie (Movie) values ('Bliss (Mutluluk)');
insert into Movie (Movie) values ('Great Freedom No. 7 (Port of Freedom) (Große Freiheit Nr. 7)');
insert into Movie (Movie) values ('Earthsea (Legend of Earthsea)');
insert into Movie (Movie) values ('Ticking Clock');
insert into Movie (Movie) values ('King''s Game (Kongekabale)');
insert into Movie (Movie) values ('No One Lives');
insert into Movie (Movie) values ('Kill Me Now');
insert into Movie (Movie) values ('Trick');
insert into Movie (Movie) values ('When the Levees Broke: A Requiem in Four Acts');
insert into Movie (Movie) values ('Indian Summer');
insert into Movie (Movie) values ('Call of the Wild, The');
insert into Movie (Movie) values ('And While We Were Here');
insert into Movie (Movie) values ('Oh, Woe Is Me (Hélas pour moi)');
insert into Movie (Movie) values ('The Fearless Four');
insert into Movie (Movie) values ('Three Colors: Blue (Trois couleurs: Bleu)');
insert into Movie (Movie) values ('Marley & Me: The Puppy Years');
insert into Movie (Movie) values ('Richard III');
insert into Movie (Movie) values ('Class of 1999 II: The Substitute');
insert into Movie (Movie) values ('Verboten!');
insert into Movie (Movie) values ('Perfect Circle, The (Savrseni krug)');
insert into Movie (Movie) values ('Riot in Cell Block 11');
insert into Movie (Movie) values ('Blame (6 Films to Keep You Awake) (Películas para no dormir: La culpa)');
insert into Movie (Movie) values ('Whitey: United States of America v. James J. Bulger');
insert into Movie (Movie) values ('Grown Up Movie Star');
insert into Movie (Movie) values ('Inside Daisy Clover');
insert into Movie (Movie) values ('Ghost Voyage');
insert into Movie (Movie) values ('Mail Early for Xmas');
insert into Movie (Movie) values ('B.T.K.');
insert into Movie (Movie) values ('Rock & Rule');
insert into Movie (Movie) values ('Day He Arrives, The (Book chon bang hyang)');
insert into Movie (Movie) values ('Mother (Madeo)');
insert into Movie (Movie) values ('Temptation of a Monk (You Seng)');
insert into Movie (Movie) values ('1612: Khroniki smutnogo vremeni');
insert into Movie (Movie) values ('The Mystery of the Leaping Fish');
insert into Movie (Movie) values ('One Piece Film Z');
insert into Movie (Movie) values ('Tequila Sunrise');
insert into Movie (Movie) values ('Impossible, The (Imposible, Lo)');
insert into Movie (Movie) values ('And So It Goes');
insert into Movie (Movie) values ('Last Holiday');
insert into Movie (Movie) values ('Kids of Survival');
insert into Movie (Movie) values ('Wrath of God, The');
insert into Movie (Movie) values ('Myn Bala: Warriors of the Steppe');
insert into Movie (Movie) values ('Beverly Hills Cop');
insert into Movie (Movie) values ('Shot in the Heart');
insert into Movie (Movie) values ('Dealin'' with Idiots');
insert into Movie (Movie) values ('Broadway');
insert into Movie (Movie) values ('Education of Little Tree, The');
insert into Movie (Movie) values ('The Chumscrubber');
insert into Movie (Movie) values ('Conceiving Ada');
insert into Movie (Movie) values ('City of Life and Death (Nanjing! Nanjing!)');
insert into Movie (Movie) values ('Star 80');
insert into Movie (Movie) values ('Behind the Sun (Abril Despedaçado)');
insert into Movie (Movie) values ('Rebound');
insert into Movie (Movie) values ('Burning Blue');
insert into Movie (Movie) values ('Song of the South');
insert into Movie (Movie) values ('I Are You, You Am Me (Tenkosei)');
insert into Movie (Movie) values ('Kennedys, The');
insert into Movie (Movie) values ('Hunter, The');
insert into Movie (Movie) values ('Material Girls');
insert into Movie (Movie) values ('My Bloody Valentine');
insert into Movie (Movie) values ('Flushed Away');
insert into Movie (Movie) values ('Ghost from the Machine (Phasma Ex Machina)');
insert into Movie (Movie) values ('Dream Machine');
insert into Movie (Movie) values ('Sanshiro Sugata (Judo Saga) (Sugata Sanshirô)');
insert into Movie (Movie) values ('Wilbur Wants to Kill Himself');
insert into Movie (Movie) values ('New York Doll');
insert into Movie (Movie) values ('Night of the Demons 2');
insert into Movie (Movie) values ('Clara''s Heart');
insert into Movie (Movie) values ('The ABCs of Death 2');
insert into Movie (Movie) values ('Variety (Varieté)');
insert into Movie (Movie) values ('Love Hina Christmas Special: Silent Eve (Rabu Hina kurisumasu supesharu: Sairento ivu)');
insert into Movie (Movie) values ('Grass Is Greener, The');
insert into Movie (Movie) values ('December 7th');
insert into Movie (Movie) values ('Tough Guys Don''t Dance');
insert into Movie (Movie) values ('Lebanon, Pa.');
insert into Movie (Movie) values ('Last Days of Disco, The');
insert into Movie (Movie) values ('Vow, The');
insert into Movie (Movie) values ('Babylon');
insert into Movie (Movie) values ('World Unseen, The');
insert into Movie (Movie) values ('Wedding Director, The (Il regista di matrimoni)');
insert into Movie (Movie) values ('The Bone Snatcher');
insert into Movie (Movie) values ('Manon of the Spring (Manon des sources)');
insert into Movie (Movie) values ('Good Morning (Ohayô)');
insert into Movie (Movie) values ('Play Girl');
insert into Movie (Movie) values ('It Happened One Night');
insert into Movie (Movie) values ('Izo');
insert into Movie (Movie) values ('We Don''t Live Here Anymore');
insert into Movie (Movie) values ('Death Warrant');
insert into Movie (Movie) values ('Letter, The');
insert into Movie (Movie) values ('Midnight');
insert into Movie (Movie) values ('What Planet Are You From?');
insert into Movie (Movie) values ('Jackass Number Two');
insert into Movie (Movie) values ('Hell and High Water');
insert into Movie (Movie) values ('Land of Milk and Honey (Pays de cocagne)');
insert into Movie (Movie) values ('This Christmas');
insert into Movie (Movie) values ('The Last Gladiators');
insert into Movie (Movie) values ('Body Double');
insert into Movie (Movie) values ('Eraser');
insert into Movie (Movie) values ('Dogs in Space');
insert into Movie (Movie) values ('Foon');
insert into Movie (Movie) values ('Painting Sellers, The (Taulukauppiaat)');
insert into Movie (Movie) values ('The Big One: The Great Los Angeles Earthquake');
insert into Movie (Movie) values ('Bob''s Birthday');
insert into Movie (Movie) values ('Sniper 2');
insert into Movie (Movie) values ('Mindwarp');
insert into Movie (Movie) values ('Chelsea Girls');
insert into Movie (Movie) values ('Hangover, The');
insert into Movie (Movie) values ('Mickey''s Once Upon a Christmas');
insert into Movie (Movie) values ('First on the Moon (Pervye na Lune)');
insert into Movie (Movie) values ('April in Paris');
insert into Movie (Movie) values ('Between Strangers');
insert into Movie (Movie) values ('Village of the Damned');
insert into Movie (Movie) values ('loudQUIETloud: A Film About the Pixies');
insert into Movie (Movie) values ('Criminal Law');
insert into Movie (Movie) values ('Thirteen Women');
insert into Movie (Movie) values ('Viy or Spirit of Evil (Viy)');
insert into Movie (Movie) values ('Gun Fury');
insert into Movie (Movie) values ('Cousinhood (Primos)');
insert into Movie (Movie) values ('Attack of the Killer Tomatoes!');
insert into Movie (Movie) values ('Hickey and Boggs');
insert into Movie (Movie) values ('Song for Martin, A (Sång för Martin, En)');
insert into Movie (Movie) values ('Mermaid, The (Rusalka)');
insert into Movie (Movie) values ('Bride Flight');
insert into Movie (Movie) values ('Diary of a Wimpy Kid: Rodrick Rules');
insert into Movie (Movie) values ('Hell in the Pacific');
insert into Movie (Movie) values ('In & Out');
insert into Movie (Movie) values ('Witness for the Prosecution');
insert into Movie (Movie) values ('Iron Man 2');
insert into Movie (Movie) values ('Adventures in Zambezia');
insert into Movie (Movie) values ('One Hour with You');
insert into Movie (Movie) values ('Edvard Munch');
insert into Movie (Movie) values ('Take, The');
insert into Movie (Movie) values ('Family United (La gran familia española)');
insert into Movie (Movie) values ('Murder of Fred Hampton, The');
insert into Movie (Movie) values ('Boy and His Dog, A');
insert into Movie (Movie) values ('Better Than Chocolate');
insert into Movie (Movie) values ('Alex in Wonderland');
insert into Movie (Movie) values ('Love Sick Love');
insert into Movie (Movie) values ('Pigs with a P.38');
insert into Movie (Movie) values ('Live from Baghdad');
insert into Movie (Movie) values ('God''s Little Acre');
insert into Movie (Movie) values ('Dragon Ball Z: Super Android 13! (Doragon bôru Z 7: Kyokugen batoru!! San dai sûpâ saiyajin)');
insert into Movie (Movie) values ('Soul Surfer');
insert into Movie (Movie) values ('Foxfire');
insert into Movie (Movie) values ('Incredibly True Adventure of Two Girls in Love, The');
insert into Movie (Movie) values ('Who''s the Caboose?');
insert into Movie (Movie) values ('Redemption (Hummingbird)');
insert into Movie (Movie) values ('6 Desires: DH Lawrence and Sardinia');
insert into Movie (Movie) values ('Kaksparsh');
insert into Movie (Movie) values ('Shaolin Temple, The (Shao Lin Si)');
insert into Movie (Movie) values ('My Mother''s Courage (Mutters Courage)');
insert into Movie (Movie) values ('Are You Scared?');
insert into Movie (Movie) values ('Constant Nymph, The');
insert into Movie (Movie) values ('Shark Alarm at Müggelsee (Hai Alarm am Müggelsee)');
insert into Movie (Movie) values ('Ideal Husband, An');
insert into Movie (Movie) values ('My Dear Desperado');
insert into Movie (Movie) values ('Scenesters, The');
insert into Movie (Movie) values ('We Are Young. We Are Strong.');
insert into Movie (Movie) values ('Slow Burn');
insert into Movie (Movie) values ('King and the Clown, The (Wang-ui namja)');
insert into Movie (Movie) values ('Hateship Loveship');
insert into Movie (Movie) values ('Arrested Development Documentary Project, The');
insert into Movie (Movie) values ('Rabbit Without Ears 2 (Zweiohrküken)');
insert into Movie (Movie) values ('Carrie');
insert into Movie (Movie) values ('Here Comes Mr. Jordan');
insert into Movie (Movie) values ('Jalla! Jalla!');
insert into Movie (Movie) values ('Adventure of Sherlock Holmes'' Smarter Brother, The');
insert into Movie (Movie) values ('Tall Blond Man with One Black Shoe, The (Le grand blond avec une chaussure noire)');
insert into Movie (Movie) values ('Saraband');
insert into Movie (Movie) values ('I Hired a Contract Killer');
insert into Movie (Movie) values ('Original Kings of Comedy, The');
insert into Movie (Movie) values ('Judex');
insert into Movie (Movie) values ('Young Bess');
insert into Movie (Movie) values ('Beyond the Border');
insert into Movie (Movie) values ('Destry Rides Again');
insert into Movie (Movie) values ('Look');
insert into Movie (Movie) values ('Cose da pazzi');
insert into Movie (Movie) values ('Better Luck Tomorrow');
insert into Movie (Movie) values ('Timber Falls');
insert into Movie (Movie) values ('The Kingdom of Dreams and Madness');
insert into Movie (Movie) values ('Lonely Hearts');
insert into Movie (Movie) values ('Macbeth');
insert into Movie (Movie) values ('Retrogade');
insert into Movie (Movie) values ('Money Talks');
insert into Movie (Movie) values ('Where Were You When the Lights Went Out?');
insert into Movie (Movie) values ('Offside');
insert into Movie (Movie) values ('Cheech & Chong''s Next Movie');
insert into Movie (Movie) values ('Fantasia');
insert into Movie (Movie) values ('She Cried No (Freshman Fall)');
insert into Movie (Movie) values ('On the Ropes');
insert into Movie (Movie) values ('Scooby-Doo! The Mystery Begins');
insert into Movie (Movie) values ('Martha');
insert into Movie (Movie) values ('Bread and Roses');
insert into Movie (Movie) values ('Pekka ja Pätkä neekereinä');
insert into Movie (Movie) values ('Surf Ninjas');
insert into Movie (Movie) values ('Great Escape: The Untold Story');
insert into Movie (Movie) values ('Two Kilers (Kilerów 2-óch)');
insert into Movie (Movie) values ('Stella Maris');
insert into Movie (Movie) values ('Thomas Crown Affair, The');
insert into Movie (Movie) values ('Last Circus, The (Balada triste de trompeta) (Sad Trumpet Ballad, A)');
insert into Movie (Movie) values ('Special Delivery');
insert into Movie (Movie) values ('Relax... It''s Just Sex');
insert into Movie (Movie) values ('This is Our Time');
insert into Movie (Movie) values ('We Steal Secrets: The Story of WikiLeaks');
insert into Movie (Movie) values ('To Have, or Not (En avoir (ou pas))');
insert into Movie (Movie) values ('Today You Die');
insert into Movie (Movie) values ('2 + 2 (Dos más dos)');
insert into Movie (Movie) values ('Passeio com Johnny Guitar');
insert into Movie (Movie) values ('Big Wedding, The');
insert into Movie (Movie) values ('Robocroc');
insert into Movie (Movie) values ('Mountain Patrol (Kekexili)');
insert into Movie (Movie) values ('It Should Happen to You');
insert into Movie (Movie) values ('Starred Up');
insert into Movie (Movie) values ('The Garden of Sinners - Chapter 5: Paradox Paradigm');
insert into Movie (Movie) values ('Highway ');
insert into Movie (Movie) values ('Dark Lurking, The');
insert into Movie (Movie) values ('Agatha Christie''s ''Ten Little Indians'' (Ten Little Indians) (And Then There Were None)');
insert into Movie (Movie) values ('Free Willy');
insert into Movie (Movie) values ('At Berkeley');
insert into Movie (Movie) values ('Day of the Dead');
insert into Movie (Movie) values ('Wings of Honneamise (Ôritsu uchûgun Oneamisu no tsubasa)');
insert into Movie (Movie) values ('Barbary Coast Gent (Gold Town) (Honest Thief, The)');
insert into Movie (Movie) values ('Eddie and the Cruisers');
insert into Movie (Movie) values ('Yeh Jawaani Hai Deewani');
insert into Movie (Movie) values ('Midnight Chronicles');
insert into Movie (Movie) values ('Cinderella');
insert into Movie (Movie) values ('Commitments, The');
insert into Movie (Movie) values ('Along Came Jones');
insert into Movie (Movie) values ('End of the Line, The');
insert into Movie (Movie) values ('Lady Snowblood (Shurayukihime)');
insert into Movie (Movie) values ('King of Kong, The');
insert into Movie (Movie) values ('Carriers');
insert into Movie (Movie) values ('Strictly Ballroom');
insert into Movie (Movie) values ('Ball of Fire');
insert into Movie (Movie) values ('Bye-Bye');
insert into Movie (Movie) values ('Unraveled');
insert into Movie (Movie) values ('Rat Race, The (Garson Kanin''s The Rat Race)');
insert into Movie (Movie) values ('Cadillac Man');
insert into Movie (Movie) values ('Mishen (Target)');
insert into Movie (Movie) values ('Ever Since the World Ended');
insert into Movie (Movie) values ('Stars');
insert into Movie (Movie) values ('Mile... Mile & a Half');
insert into Movie (Movie) values ('Eden');
insert into Movie (Movie) values ('Deceived');
insert into Movie (Movie) values ('3, 2, 1... Frankie Go Boom (Frankie Go Boom)');
insert into Movie (Movie) values ('Darling');
insert into Movie (Movie) values ('Calendar Girl');
insert into Movie (Movie) values ('Little Fish');
insert into Movie (Movie) values ('Kids in the Hall: Same Guys, New Dresses');
insert into Movie (Movie) values ('Larceny, Inc.');
insert into Movie (Movie) values ('Questioning Darwin');
insert into Movie (Movie) values ('Charlie Chan''s Courage');
insert into Movie (Movie) values ('Yella');
insert into Movie (Movie) values ('Funny Face');
insert into Movie (Movie) values ('Diamond Dogs');
insert into Movie (Movie) values ('Green Wave, The');
insert into Movie (Movie) values ('Amen');
insert into Movie (Movie) values ('Helter Skelter');
insert into Movie (Movie) values ('Hunting of the President, The');
insert into Movie (Movie) values ('Queen of Montreuil');
insert into Movie (Movie) values ('Ringer, The');
insert into Movie (Movie) values ('Besieged (a.k.a. L'' Assedio)');
insert into Movie (Movie) values ('Strange One, The');
insert into Movie (Movie) values ('City of Hope');
insert into Movie (Movie) values ('Mistress of Spices, The');
insert into Movie (Movie) values ('Round Up, The (La Rafle)');
insert into Movie (Movie) values ('Brick Mansions');
insert into Movie (Movie) values ('This American Journey');
insert into Movie (Movie) values ('Interrupters, The');
insert into Movie (Movie) values ('Black Sea');
insert into Movie (Movie) values ('Aerial Gunner');
insert into Movie (Movie) values ('Ping Pong');
insert into Movie (Movie) values ('Eye Above the Well, The (Het oog boven de put)');
insert into Movie (Movie) values ('Ivanhoe');
insert into Movie (Movie) values ('Great Locomotive Chase, The');
insert into Movie (Movie) values ('Thank Your Lucky Stars');
insert into Movie (Movie) values ('Twilight Zone: The Movie');
insert into Movie (Movie) values ('Saint John of Las Vegas');
insert into Movie (Movie) values ('Following');
insert into Movie (Movie) values ('Last Castle, The');
insert into Movie (Movie) values ('Raise Your Voice');
insert into Movie (Movie) values ('Amazing Johnathan: Wrong on Every Level');
insert into Movie (Movie) values ('Slumber Party Massacre III');
insert into Movie (Movie) values ('Jerry and Tom');
insert into Movie (Movie) values ('Glenn Killing på Berns');
insert into Movie (Movie) values ('Guilty (Présumé coupable)');
insert into Movie (Movie) values ('Bellflower');
insert into Movie (Movie) values ('The Orkly Kid');
insert into Movie (Movie) values ('Yu-Gi-Oh!: Bonds Beyond Time (Gekijouban Yuugiou: Chouyuugou! Jikuu o koeta kizuna)');
insert into Movie (Movie) values ('Mongolian Ping-Pong (Lü cao di)');
insert into Movie (Movie) values ('Pawn');
insert into Movie (Movie) values ('Splendor');
insert into Movie (Movie) values ('Mouse That Roared, The');
insert into Movie (Movie) values ('Back from Eternity');
insert into Movie (Movie) values ('Music in the Air');
insert into Movie (Movie) values ('Canned Dreams (Säilöttyjä unelmia)');
insert into Movie (Movie) values ('Devil Times Five (a.k.a. Peopletoys)');
insert into Movie (Movie) values ('My Favorite Season');
insert into Movie (Movie) values ('Bridegroom');
insert into Movie (Movie) values ('White Hunter, Black Heart');
insert into Movie (Movie) values ('Have Dreams, Will Travel');
insert into Movie (Movie) values ('Orca: The Killer Whale');
insert into Movie (Movie) values ('Sunburn');
insert into Movie (Movie) values ('Tidal Wave');
insert into Movie (Movie) values ('Tampopo');
insert into Movie (Movie) values ('Fata Morgana');
insert into Movie (Movie) values ('Secret Agent, The');
insert into Movie (Movie) values ('Tron');
insert into Movie (Movie) values ('Undefeated, The');
insert into Movie (Movie) values ('Dr. Goldfoot and the Girl Bombs (Le spie vengono dal semifreddo)');
insert into Movie (Movie) values ('Volcano (Eldfjall)');
insert into Movie (Movie) values ('Apostle, The');
insert into Movie (Movie) values ('Joe Strummer: The Future Is Unwritten');
insert into Movie (Movie) values ('Games');
insert into Movie (Movie) values ('Mulholland Drive');
insert into Movie (Movie) values ('Little Murders');
insert into Movie (Movie) values ('Bionicle: Mask of Light (Bionicle: Mask of Light - The Movie)');
insert into Movie (Movie) values ('Gone');
insert into Movie (Movie) values ('Scrooge');
insert into Movie (Movie) values ('Death on the Staircase (Soupçons)');
insert into Movie (Movie) values ('Once My Mother');
insert into Movie (Movie) values ('Jaguar');
insert into Movie (Movie) values ('Surfer, Dude');
insert into Movie (Movie) values ('Rewind This!');
insert into Movie (Movie) values ('The Thief');
insert into Movie (Movie) values ('Texas Chainsaw Massacre 2, The');
insert into Movie (Movie) values ('Blow Dry (a.k.a. Never Better)');
insert into Movie (Movie) values ('Soldier''s Plaything, A');
insert into Movie (Movie) values ('Darjeeling Limited, The');
insert into Movie (Movie) values ('About Cherry');
insert into Movie (Movie) values ('Johnny Express');
insert into Movie (Movie) values ('Against the Ropes');
insert into Movie (Movie) values ('Deuces Wild');
insert into Movie (Movie) values ('Coach Carter');
insert into Movie (Movie) values ('90 Minutes (90 minutter)');
insert into Movie (Movie) values ('Alice (Neco z Alenky)');
insert into Movie (Movie) values ('Under the Age');
insert into Movie (Movie) values ('Hitch-Hiker, The');
insert into Movie (Movie) values ('And Starring Pancho Villa as Himself');
insert into Movie (Movie) values ('Rosetta');
insert into Movie (Movie) values ('Remo Williams: The Adventure Begins');
insert into Movie (Movie) values ('Heartbeats (Kohtaamisia)');
insert into Movie (Movie) values ('Persona non grata');
insert into Movie (Movie) values ('China Syndrome, The');
insert into Movie (Movie) values ('Seabiscuit');
insert into Movie (Movie) values ('In Their Sleep (Dans ton sommeil)');
insert into Movie (Movie) values ('Scream of Fear (a.k.a. Taste of Fear)');
insert into Movie (Movie) values ('Paintball');
insert into Movie (Movie) values ('Man from London, The (A Londoni férfi)');
insert into Movie (Movie) values ('Flim-Flam Man, The');
insert into Movie (Movie) values ('Soap and Water');
insert into Movie (Movie) values ('A Run for Your Money');
